import 'package:tourismappofficial/Places/place.dart';


class Hotels {
  List<Place> famagustaHotels = [
    Place(name: 'Chrysomare Beach Hotel & Resort', imagePath: 'FamagustaHotels/chrysomare.jpg', lat: 34.98735919209693, long: 33.98336388434142, id: 39, city: 'Ayia Napa, Famagusta',category: '5 Star Hotel ', description: "Chrysomare Beach Hotel & Resort, a luxurious 5-star property in Ayia Napa, Cyprus, offers beachfront accommodation with landscaped gardens, three restaurants and bars, smart room facilities, spa and fitness centers, kids club with activities and splash pool, and is close to local amenities (photo from booking)."),
    Place(name: 'Pavlo Napa Beach Hotel', imagePath: 'FamagustaHotels/pavlo.jpg', city:'Ayia Napa, Famagusta' , lat: 34.9890591381017, long: 33.97918139834978, id: 40 , category: '4 Star Hotel', description: 'Pavlo Napa Beach Hotel, a family-friendly beachfront property in Ayia Napa, Cyprus, offers air-conditioned rooms with modern amenities, indoor and outdoor pools, a fitness center, and on-site dining. Located close to local shops, restaurants, and bars, it\'s favored for its excellent location and facilities (photo from Tripadvisor' ),
    Place(name: 'Melpo Antia Hotel & Suites', imagePath: 'FamagustaHotels/melpo hotel.jpg', lat: 34.9868827520948, long: 34.0003469015252, city: 'Ayia Napa, Famagusta', category: '4 Star Hotel', id: 42, description: 'Melpo Antia Hotel & Suites in Ayia Napa is a popular 4-star hotel known for its stylish and luxurious amenities. The hotel has undergone various transformations since its inception in the 1980s, evolving from a small family apartment hotel to its current sophisticated phase. It boasts 200 recently renovated luxury hotel rooms, studios, and one-bedroom apartments, designed to cater to the diverse needs of its guests.The hotel\'s state-of-the-art wellness center offers a range of spa therapies and treatments for those seeking relaxation and peace. Additionally, a well-equipped gym area is available for fitness enthusiasts.Dining at Melpo Antia is a unique culinary experience, with a variety of dining options available at their premium restaurants and cafes. The hotel includes Avra Meze Restaurant, Frankie\'s Bar & Grill, Megu - a Japanese restaurant, and The Bakery Co.'),
    Place(name: 'Cosmo Napa Boutique Hotel', imagePath: 'FamagustaHotels/cosmo.jpg',city:'Ayia Napa, Famagusta', lat:34.991827908754175,long: 33.996824873948306,category: '3 Star Hotel', description: 'The Cosmo Napa Boutique Hotel in Ayia Napa, Cyprus, is a modern city hotel that offers personalized service and authentic hospitality. It\'s conveniently located in the heart of Ayia Napa, close to the area\'s main attractions, yet situated in a quiet spot.The hotel consists of 100 rooms, including standard or superior rooms, junior suites, and a deluxe suite. These accommodations come with full air conditioning, soundproofing, spacious bathrooms (most with balconies, some with pool views), free Wi-Fi, a safe box, and electric key locks. Catering facilities in the rooms include a refrigerator, microwave, kettle, and toaster, although no cookers are available.Guests can relax by the outdoor swimming pool, complemented by sun loungers, and enjoy services at the chill-out pool bar, a breakfast and snack restaurant, a lounge, and sunbathing facilities. The hotel also organizes chill-out evenings with low-volume atmospheric music, and guests can enjoy various lifestyle events during their stay (photo from Booking).'  ),
    Place(name: 'Nissiana Hotel & Bungalows', imagePath: 'FamagustaHotels/nissiana.jpg', lat: 34.99073764298732, long:33.969950196579006, id: 43, city: 'Ayia Napa, Famagusta', category: '3 Star Hotel', description: 'The Nissiana Hotel & Bungalows in Ayia Napa, Cyprus, is a modern 3-star resort located just 150 meters from the famous Nissi Beach, known for its beautiful white sandy shore. The hotel is situated in a prime location that offers easy access to the beach and is about 25 minutes walking distance from the center of Ayia Napa.Accommodations at Nissiana Hotel include a variety of room types such as standard and superior double rooms, studios, family rooms, and bungalows, catering to different guest needs. These rooms are designed to accommodate anywhere from two to four persons, with configurations of single beds, futon beds, and sofa beds. While specific amenities vary, standard features include air conditioning, a safe box, Wi-Fi, satellite TV, a telephone, and a hair dryer. Most rooms come with balconies, and there are options for rooms without balconies at reduced rates (phto from Booking).'),
    Place(name: 'Amarande', imagePath: 'FamagustaHotels/amarande.jpg', lat:  34.98591948413279, long: 34.01430996774387, id: 44, category: '5 Star Hotel', city: 'Ayia Napa, Famagusta',description: 'The Amarande in Ayia Napa is a 5-star adults-only resort known for its luxury and comfort. It\'s conveniently located just 984 feet from Ayia Napa Beach and about 0.6 miles from the center of Ayia Napa, offering guests easy access to both the beach and local attractions.Accommodations at the Amarande include rooms with spacious infinity glass balconies, many of which offer sea views. All rooms are equipped with modern amenities such as flat-screen satellite TV, a room automation panel system, USB charging points, and bathrooms with double sink vanity sets. Guests can enjoy free WiFi throughout the hotel (photo from TripAdvisor).' ),
    Place(name: 'Alion Beach Hotel', imagePath: 'FamagustaHotels/alion.jpg', lat: 34.98460786021664, long: 34.01082808099375, id: 45, category: '5 Star Hotel', city: 'Ayia Napa, Famagusta', description: 'The Alion Beach Hotel in Ayia Napa, Cyprus, is a renowned 5-star hotel known for its luxurious facilities and exceptional service. It\'s located in a prime area, providing direct access to the sandy Grecian Bay, making it an ideal choice for those seeking a beachfront experience.Accommodations at the Alion Beach Hotel are designed to offer comfort and elegance. Guests can choose from various room types, many featuring panoramic views of the Mediterranean Sea or the surrounding park. The rooms are well-equipped with modern amenities, ensuring a comfortable stay (photo from Tripadvisor).'),
    Place(name: 'Amanti, MadeForTwo Hotels', imagePath:'FamagustaHotels/Amanti, MadeForTwo Hotels.jpg', lat: 34.98825801833854,long: 34.00618111929517, id: 46, category: '5 Star Hotel', city: 'Ayia Napa, Famagusta', description: 'The Alion Beach Hotel in Ayia Napa, Cyprus, is a renowned 5-star hotel known for its luxurious facilities and exceptional service. It\'s located in a prime area, providing direct access to the sandy Grecian Bay, making it an ideal choice for those seeking a beachfront experience.Accommodations at the Alion Beach Hotel are designed to offer comfort and elegance. Guests can choose from various room types, many featuring panoramic views of the Mediterranean Sea or the surrounding park. The rooms are well-equipped with modern amenities, ensuring a comfortable stay (photo from Tripadvisor).' ),
    Place(name: 'The Blue Ivy Hotel & Suites', imagePath: 'FamagustaHotels/the-blue-ivy-hotel-suites.jpg', lat: 35.01859324430639, long:34.04919814570064, id: 47,city: 'Protaras, Famagusta', category: '5 Star Hotel', description:'The Blue Ivy Hotel and Suites, located in Protaras, Cyprus, is a stylish and lavish addition to the Sunnyseeker Hotels chain. It offers a unique blend of elegance, comfort, and a relaxed atmosphere with its modern and sophisticated design. The hotel is ideally positioned close to the spectacular white sands and crystal-clear waters of the award-winning Blue Flag Sunrise Beach, as well as the center of Protaras.' ),
    Place(name: 'Sunrise Beach Hotel', imagePath: 'FamagustaHotels/sunrise.jpg', lat: 35.0161111435364, long: 34.05408239599369, id: 48, category: '4 Star Hotel', city: 'Protaras, Famagusta', description:'The Sunrise Beach Hotel in Protaras is highly regarded for its excellent location and quality services. With an overall rating of 8.6/10, it boasts a superb location score of 9.7/10, indicating its prime beachfront setting. The hotel offers various facilities including a lagoon-style pool with a hot tub and swim-up bar, modern rooms with balconies overlooking the pool and the Mediterranean Sea, free Wi-Fi, and air conditioning. Guests have particularly praised the hotel\'s cleanliness, comfort, friendly staff, and the quality of food served, especially the dinner. This hotel is popular among couples and is known for providing a relaxing beachfront holiday experience.' ),
    Place(name: 'Crystal Springs Beach Hotel', imagePath:'FamagustaHotels/crystal-springs-beach.jpg', lat: 35.04382501169545, long: 34.033774473513176, id: 49, category: '4 Star Hotel', city: 'Protaras, Famagusta', description: 'The Crystal Springs Beach Hotel, located near Protaras, Cyprus, offers a serene and picturesque experience just outside the bustling resort town. It\'s situated in a peaceful setting, providing intimacy away from large crowds while still being conveniently close to Protaras (2km), Paralimni (5km), and Ayia Napa (10km), as well as neighboring traditional villages.' )
  ];

  List<Place> limassolHotels = [
    Place(name: 'Alasia Hotel', imagePath: 'LimassolHotels/alasia.jpg', lat: 34.68150278510444, long:33.03002617508021,  id: 50, city: 'Limassol',category: '4 Star Hotel', description: 'The Alasia Hotel, nestled in the heart of Limassol, Cyprus, is a testament to luxury and elegance. It stands out as a lavish boutique hotel that offers a serene escape from city life. Architect Sotiris Psaras has skillfully transformed the recently renovated building into a modern, dream-like world that epitomizes smart, refined luxury. The hotel\'s design features innovative architecture, including the absence of conventional walls and a floor-to-ceiling glass facade, which bathes the indoor/outdoor lobby in natural light, creating a sophisticated and original environment​​.The hotel has received glowing reviews for its facilities, cleanliness, comfort, and overall value for money. Guests particularly appreciate the attentive staff and the hotel\'s excellent location in Limassol. The Alasia Hotel offers an array of amenities, including two onsite restaurants that provide international cuisine, a poolside bar, and a terrace. It also boasts an indoor and an outdoor pool, with sun loungers and pool umbrellas for guests to relax. For those seeking pampering, The Spa at the hotel offers deep-tissue massages, reflexology, and body scrubs, among other treatments (photo from TripAdvisor).'),
    Place(name: 'Odysseia Hotel Kapetanios', imagePath: 'LimassolHotels/odysseia hotel.jpg', lat: 34.68578347202869,long: 33.060602225403876, id: 51, city: 'Limassol', category: '3 Star Hotel', description: 'The Kapetanios Odysseia Hotel, situated in a central area of Limassol, Cyprus, offers a blend of convenience and comfort for both holidaymakers and business travelers. Located just 100 meters from the beach, the hotel is within walking distance of several attractions, including the Limassol Zoo, Municipal Gallery, the Archaeological Museum, and the old city center.The hotel underwent extensive renovations in 2015/16 and boasts 159 rooms designed to provide urban comfort. Superior rooms offer additional space and privacy with large terraces or balconies featuring sunbathing facilities. Room amenities include international direct dial telephones, satellite TV, air-conditioning and heating, mini-bars, safe boxes, and facilities for tea and coffee. The hotel also provides a range of facilities such as a lobby, two restaurants, a bar, a pool bar, a renovated swimming pool with a jacuzzi (heated in winter), a children\'s pool, a playground, a health club, and two conference rooms equipped with modern technical equipment (photo from TripAdvisor).' ),
    Place(name: 'Amathus Beach Hotel Limassol ', imagePath: 'LimassolHotels/amathus.jpg', lat: 34.70957020852758, long: 33.1335700211301, id: 52, category: '5 Star Hotel', city: 'Limassol', description: 'The Amathus Beach Hotel in Limassol, Cyprus, is a luxurious 5-star beachfront resort known for its world-class comfort and serene sanctuary. As a member of the Leading Hotels of the World, it offers state-of-the-art facilities, exceptional services, and is recognized as one of the Leading Spas of the World. The hotel has been praised for its excellent amenities, making it a top choice for wellness, romance, family, and luxury experiences.The hotel\'s accommodations include superior rooms with either inland or sea views, family rooms, and a variety of suites. These options range from standard rooms to more luxurious offerings like the Presidential Suite, ensuring comfort and luxury for every guest. The rooms and suites are appointed with high-quality furnishings and contemporary amenities, blending comfort with luxury. Additionally, several suites come with private pools, adding an extra touch of exclusivity (photo from Booking).' )
    ,Place(name: 'Sunquest Gardens Holiday Resort', imagePath: 'LimassolHotels/germasogia.jpg', lat: 34.700910081302574, long:33.09666246714845, id: 53, city: 'Limassol', category: '3 Star Hotel', description: 'Sunquest Gardens Holiday Resort in Limassol, Cyprus, offers a pleasant stay with its convenient location and range of amenities. Situated in Potamos Germasoggia, it\'s only 400 meters from a sandy beach, ensuring easy access to seaside relaxation. The resort features a swimming pool and an on-site restaurant, catering to guests\' dining and recreational needs.The accommodations at Sunquest Gardens include studios and apartments with one or two separate bedrooms, each with a furnished balcony overlooking the garden. The units are equipped with modern kitchens that include a microwave, stove, fridge, and dining area, providing guests with the option of self-catering. Additional room features include leather sofas, an LCD satellite TV, and air conditioning (photo from Booking).'),
    Place(name: 'Kapetanios Limassol Hotel', imagePath: 'LimassolHotels/kapetanios.jpg', lat: 34.68476532885884, long:33.05871490210141, id: 54, category: '3 Star Limassol', description: 'Kapetanios Limassol Hotel, located in Limassol, Cyprus, is a superior 3-star hotel situated just 100 meters from the beach. The hotel offers 140 rooms spread across two buildings, each featuring a private balcony, air conditioning, direct dial telephone, digital safe box, satellite TV, mini fridge, kettle facilities, hairdryer, and free Wi-Fi in all areas. The hotel is popular for its quality and comfort.Guest reviews indicate a good overall experience with an average rating of 7.8 out of 10. The staff is appreciated for their friendliness and helpfulness, scoring 8.4 out of 10. The hotel\'s facilities, cleanliness, comfort, value for money, and location have also received positive remarks. Its location is particularly well-rated at 8.8 out of 10, as it\'s conveniently near the beach and city center (photo from Booking)'),
    Place(name: 'NYX Hotel Limassol By Leonardo Hotels', imagePath: 'LimassolHotels/nyx.jpg', lat: 34.67508632569828, long: 33.047942886414795, id: 55, category: '4 Star Hotel', city: 'Limassol', description: 'The NYX Hotel Limassol by Leonardo Hotels in Cyprus has garnered positive feedback for its overall experience, boasting an excellent rating of 8.6 out of 10. Guests have particularly praised the hotel\'s staff, facilities, cleanliness, comfort, value for money, and location, with the staff receiving a high score of 9.1 out of 10. The hotel\'s location is especially notable, with a score of 9.4, indicating its convenience for guests who wish to explore Limassol.Facilities at the NYX Hotel include an outdoor swimming pool, fitness center, a shared lounge, and a restaurant serving Mediterranean and Asian cuisine. The hotel also offers free Wi-Fi, air-conditioned rooms equipped with modern amenities, and a wellness area that includes a hammam and a hot spring bath (photo from Booking).'  )

  ];

  List<Place> nicosiaHotels = [
    Place(name: 'Hilton', imagePath: 'NicosiaHotels/hilton.jpg', lat: 35.1631982506298,long: 33.327135513768525,  id: 56, city: 'Nicoisia', category: '5 Star Hotel', description: 'The Hilton Nicosia in Cyprus is a well-rated hotel, known for its excellent facilities and services. It has an average rating of 8.5 out of 10 from guests, with particular praise for its staff, facilities, cleanliness, comfort, and value for money. The hotel is noted for its convenient location in the center of Nicosia City, making it a great choice for both business and leisure travelers.Guests have access to a variety of amenities, including free private parking, free WiFi throughout the property, and stylish, elegantly decorated rooms with private balconies offering pool or city views. The rooms are equipped with modern comforts such as air conditioning, flat-screen TVs, and luxurious bathrooms.The hotel offers several dining options, including the Olympia Restaurant for local and international cuisine, the Akakiko Restaurant for Japanese dining, and To Elliniko for Greek gourmet dining. The Mint Bar and Sorrento Pool Bar are available for drinks. For relaxation, there\'s a lagoon-shaped swimming pool and a state-of-the-art fitness center. The hotel also boasts a full-service spa offering a range of treatments, a relaxation pool, and fitness center.'),
    Place(name: 'Map Boutique Hotel', imagePath: 'NicosiaHotels/map.jpg', lat: 35.16855984021973, long:33.36294463832894, id: 57, category: '5 Star Hotel', city: 'Nicosia', description:'The MAP Boutique Hotel in Nicosia, Cyprus, is a highly rated accommodation choice, known for its excellent service and facilities. It has received a remarkable rating of 9.4 out of 10 from guests on Booking.com, indicating a very positive overall guest experience. The hotel is praised for its high standards in staff service, facilities, cleanliness, comfort, and value for money. Additionally, its location is particularly appreciated by guests, making it an ideal choice for those looking to explore Nicosia.The hotel offers a range of amenities including free WiFi, a fitness center, a terrace, a restaurant, and a spa. The rooms are well-equipped with modern conveniences such as air conditioning, a flat-screen TV, a balcony, and a private bathroom. A continental breakfast is available daily at the hotel, and guests have access to room service and a 24-hour front desk.' ),
    Place(name: 'The Landmark Nicosia', imagePath: 'NicosiaHotels/TheLandMark.jpg', lat: 35.15934584378223, long:33.37199582726373, city: 'Nicosia', category: '5 Star Hotel', id: 58, description: 'The Landmark Nicosia in Cyprus offers a range of comfortable and luxurious accommodation options. Their King Guest room and Twin Guest Room Pool View are both equipped with premium bedding, minibar, in-room safe, and free toiletries. For families or those seeking more space, the Family Room and various suites, including the Deluxe Suite (King) and Presidential Suite, provide ample room and added luxury. All rooms come with city views and are designed with comfort and elegance in mind. The hotel also features an indoor pool, free parking, and other amenities to enhance your stay (photo from Tripadvisor)'),
    Place(name: 'Madama Residence', imagePath: 'NicosiaHotels/madama.jpg', lat:35.17203217357559, long:33.3621101524108 , id: 59, city: 'Nicosia', category: '5 Star Hotel', description: 'The Madama Residence in Nicosia, Cyprus, is a highly-rated boutique hotel, boasting an impressive score of 9.3 out of 10 from guests. It is celebrated for its exceptional staff, quality facilities, high cleanliness standards, comfort, and good value for money. The location of the hotel is particularly appreciated by guests, earning a score of 9.2 out of 10.The hotel is located in the heart of Nicosia’s vibrant and atmospheric Old Town, occupying a building that was once Cyprus’ first bakery and mill. This heritage site has been transformed into a luxurious and contemporary accommodation option. The hotel offers six high-end suites, each with its own unique character and style, providing a sophisticated, adults-only haven. The suites blend tradition, comfort, and style in a harmonious balance( photo from Booking).')
  ];

  List<Place> paphosHotels = [
    Place(name: 'Amavi, MadeForTwo Hotels', imagePath: 'paphoshotels/amavi.jpg', city: 'Paphos', category: '5 Star Hotel', lat: 34.75124654633682,  long: 32.42179852540598, id: 60, description: 'The Amavi Hotel, part of the MadeForTwo Hotels brand in Paphos, Cyprus, is an adults-only, five-star luxury resort. It\'s designed specifically for couples, offering a romantic and relaxing atmosphere. Located on the Paphos seafront, the hotel provides unobstructed sea views and enchanting sunsets. The hotel features a variety of facilities, including a spa and wellness center, several dining options with a dine-around experience, and bars. The accommodation options at the Amavi are tailored to provide an intimate and luxurious experience for couples( photo from TripAdvisor).'),
    Place(name: 'Olympic Lagoon Resorts', imagePath: 'paphoshotels/olympic-lagoon-resort.jpg', city: 'Paphos', category: '5 Star Hotel' , lat: 34.74680744518025, long:32.42600569782882, id: 61, description:  'The Olympic Lagoon Resorts in Paphos, Cyprus, offers a five-star, all-inclusive luxury experience. It\'s located by the golden sands of a Blue Flag beach and provides a perfect holiday destination for all ages, combining entertainment, relaxation, gastronomy, and fun. The resort features a range of themed restaurants, bars, and five swimming pools, catering to both families and couples. It also boasts a comprehensive entertainment program, including musical shows, activities, and clubs for kids and teens (photo from TripAdvisor).'),
    Place(name: 'Avlida Hotel', imagePath: 'paphoshotels/avlida.jpg', lat: 34.7778816445652,long: 32.4078998076369, id: 62, city: 'Paphos', category: '4 Star Hotel', description:   'The Avlida Hotel in Paphos, Cyprus, is a four-star resort known for its blend of luxury, comfort, and affordability. It underwent a major expansion in 1992 and was completely renovated in 2013, with another refurbishment of all rooms in 2019. The hotel offers spacious rooms with modern amenities, including smart HD TVs, ultra-fast Wi-Fi, and powerful rain-showers. Located just two minutes from a sandy beach and opposite the UNESCO World Heritage Site of "Tombs of the Kings", it provides breathtaking views of the Mediterranean Sea and is conveniently close to shops, pubs, bars, restaurants, and the Paphos Harbour. The hotel caters to all-inclusive customers with a variety of cocktails, drinks, and an entertainment program')
    ,Place(name: 'Latchi Escape Hotel and Suites ', imagePath: 'paphoshotels/latchi.jpg', lat: 35.03776580083199, long:32.37493921007598, id: 63, category: '4 Star Hotel', city: 'Latchi, Paphos', description: 'The Latchi Escape Hotel & Suites, situated in the heart of the Latchi area in Neo Chorio village, is about 1.5 miles from Latchi beach. This 4-star resort offers modern and well-equipped rooms for both couples and families. It features a breakfast restaurant, a seasonal pool bar with a terrace, a large outdoor swimming pool, and an indoor pool with fresh water. The accommodation options include studios with private pools, one-bedroom suites with jacuzzis, and two-bedroom suites, some with private pools. The hotel is designed to provide a blend of natural beauty and comfort, ensuring an unforgettable holiday experience.'),
    Place(name: 'Amphora Hotel & Suites', city: 'Paphos', category: '4 Star Hotel', lat:34.74785383729554, long:32.42442116773617, id: 69, imagePath: 'paphoshotels/amphora.jpg', description: 'The Amphora Hotel & Suites in Paphos, Cyprus, is a luxurious hotel offering a tranquil and serene beachfront setting. Situated at the site of the former SODAP Winery, the hotel boasts contemporary elegance and a rejuvenating atmosphere. It features 95 Luxury Suites, spacious Superior Rooms, and a 3 Bedroom Villa, most of which provide unobstructed views of the Mediterranean Sea and the Paphos castle.The hotel offers an array of facilities to cater to guests leisure and relaxation needs. The kidney-shaped pool, complemented by a poolside bar, is a highlight, along with a children\'s pool and playground equipment on the lawns. Guests can also enjoy free introductory scuba lessons in the pool. For dining, the hotel restaurant offers both indoor and outdoor seating with an international and traditional Cypriot menu, and a hot and cold buffet breakfast is available for an additional fee. The Amphora also boasts a private beach, perfect for snorkeling, and a beachfront Ouzeri for light local fare and drinks.' ),
    Place(name: 'Capital Coast Resort And Spa', imagePath: 'paphoshotels/spa.jpg', lat:34.78286169738411, long:32.40358592113245, id: 66, category: '4 Star Hotel', city: 'Paphos', description: 'Capital Coast Resort & Spa, located in Paphos, Cyprus, offers a range of amenities for a comfortable and enjoyable stay. The resort features two large outdoor pools and a children\'s pool, surrounded by spacious decks and lawns with cushioned wooden loungers and umbrellas. Additionally, there\'s a poolside bar, a rooftop lounge with panoramic Mediterranean views, and live entertainment several evenings a week. The main restaurant serves both international and traditional Cypriot fare, with the option of private chef service in suites or for a romantic dinner on the beach.The Anemones Spa at the resort includes an indoor pool, steam room, hot tub, and Finnish sauna, along with a variety of treatments. For fitness enthusiasts, there\'s a well-equipped fitness center and sports facilities including a grass tennis court and water sports options like boat rental, windsurfing, snorkeling, and scuba diving (for an additional fee). The resort also offers bike rentals, a game room with various activities, and event planning services (photo from Booking).' ),
    Place(name: 'Theo Sunset Bay Hotel', imagePath: 'paphoshotels/sunset.jpg', id: 67, lat: 34.82896119352073, long: 32.39186974259214, city: 'Kissonegra, Paphos', category: '4 Star Hotel', description: 'Theo Sunset Bay Holiday Village is a mid-range apartment hotel situated in Paphos, Cyprus, offering a variety of accommodations and amenities. The hotel is housed in a series of two-story whitewashed buildings, set amidst beautiful Mediterranean gardens. It is conveniently located between Coral Bay and Paphos, offering easy access to local attractions and a coastal experience.Rooms at Theo Sunset Bay Holiday Village are bright and well-maintained, featuring cherry-finish furniture, cream-colored tile floors, and plush sleeper sofas. Each room is equipped with air-conditioning, free Wi-Fi, satellite TV, and furnished balconies, many of which offer stunning sea views. The larger rooms include fully equipped kitchenettes with amenities such as mini-fridges, microwaves, stoves, and kettles.'),
    Place(name: 'King Jason Paphos', imagePath: 'paphoshotels/king.jpg', lat: 34.76199095379352, long:32.42116429539904, id: 64, city: 'Paphos', category: '4 Star Hotel', description: 'The King Jason Paphos is a 4-star plus elegance hotel in Cyprus, tailored for adults and designed for stress-free holidays. It\'s conveniently located near Paphos Medieval Castle and harbour, about 2 km away, and offers easy access to UNESCO heritage archaeological sites and traditional villages. The hotel focuses on providing a peaceful, welcoming atmosphere and genuine hospitality, with a respect for nature and local communities. It features upgraded all-inclusive holidays and is known for its excellent service and comfortable accommodations in a prime Paphos location (photos from Tripadvisor)'),
    Place(name: 'Leonardo Plaza Cypria Maris Beach Hotel & Spa', imagePath: 'paphoshotels/leo.jpg', lat: 34.741864553839086, long: 32.43147499657086 , id: 68, category: '4 Star Hotel', city: 'Geroskipou, Paphos', description: 'Theo Sunset Bay Holiday Village is a mid-range apartment hotel situated in Paphos, Cyprus, offering a variety of accommodations and amenities. The hotel is housed in a series of two-story whitewashed buildings, set amidst beautiful Mediterranean gardens. It is conveniently located between Coral Bay and Paphos, offering easy access to local attractions and a coastal experience.Rooms at Theo Sunset Bay Holiday Village are bright and well-maintained, featuring cherry-finish furniture, cream-colored tile floors, and plush sleeper sofas. Each room is equipped with air-conditioning, free Wi-Fi, satellite TV, and furnished balconies, many of which offer stunning sea views. The larger rooms include fully equipped kitchenettes with amenities such as mini-fridges, microwaves, stoves, and kettles.' )
    ,Place(name: 'Elysium Hotel', imagePath: 'paphoshotels/elysium.jpg', lat: 34.77173595022233, long: 32.406528451224936, id: 65, category: '5 Star Hotel', city: 'Paphos ', description: 'The Elysium Hotel in Paphos, Cyprus, is a luxury five-star hotel known for its world-class spa, private beach, and stunning views. It caters to both leisure and business visitors and is ideal for a couple’s romantic getaway or as a venue for weddings and anniversaries. The hotel boasts a variety of accommodations, including lavish rooms, suites, and villas. Guests can enjoy a range of facilities, such as indoor and outdoor pools, tennis courts, scuba diving, and personal training programs. There are also five exquisite restaurants serving international cuisine, two bars, and a café (photo from Tripadvisor).' )
  ];

  List<Place> larnacaHotels = [
    Place(name: 'Radisson Blu Hotel', imagePath: 'larncacahotels/radisson.jpg', lat: 34.93175702107651, long:33.636984742528384, id: 69, description: 'Radisson Blu is an upscale hotel brand known for its memorable, stylish, and purposeful design. The essence of Radisson Blu is seen in every aspect of the hotel experience, emphasizing unparalleled service, comfort, and style while creating meaningful and memorable experiences for guests. Their focus is on inspiring unforgettable experiences with attention to small details, such as high-quality bedding, complimentary Wi-Fi, and well-crafted dining options. Radisson Blu properties are designed to be stylish and elegant, providing an inviting ambience with thoughtful touches (photo from Tripadvisor).', city: 'Larnaca', category: '5 Star Hotel'),
    Place(name: 'The Ciao Stelio Deluxe Hotel', imagePath: 'larncacahotels/entrance.jpg', category: '5 Star Hotel', lat: 34.893274872846,long: 33.63852205424563, id: 70, city: 'Larnaca', description: 'The Ciao Stelio Deluxe Hotel, an adults-only establishment, is renowned for its luxurious boutique hotel experience. Located in Larnaca, Cyprus, this hotel is positioned opposite the Blue Flag-certified Mackenzie Beach, which is famous for its vibrant nightlife. The hotel is conveniently situated just 4 km from Larnaca International Airport and is within easy walking distance of Finikoudes Beach Front (Fig Tree Promenade).Guests of The Ciao Stelio Deluxe Hotel enjoy a range of high-quality amenities and services. The hotel offers elegantly designed rooms and suites, many of which come with balconies and some that offer sea views. These accommodations are well-appointed with upscale amenities like flat-screen TVs, minibars, and luxurious bathroom facilities (photo from Tripadvisor).',),
    Place(name: 'The Golden Bay Beach Hotel', imagePath: 'larncacahotels/goldenbay.jpg', lat: 34.97762121009387,long: 33.69204514997375,  id: 71, category: '5 Star Hotel',city: 'Dhekelia, Larnaca', description: 'The Golden Bay Beach Hotel is a 5-star luxury hotel located in Larnaca, Cyprus. Situated at the edge of Larnaca\'s tourist area, it is perfectly positioned just 10 km from the city center and 15 km from Larnaca International Airport. The hotel is known for its excellent facilities, luxurious surroundings, impeccable hospitality, and haute cuisine. Set in mature landscaped gardens, the hotel offers a serene and picturesque setting.The hotel\'s accommodations include a range of rooms and suites, offering options like Standard side sea view and inland view rooms, Superior Sea view and Pool view rooms, Front sea view rooms, Mini Suites, Grand Suites, and a Presidential Suite. These rooms are spacious, bright, and equipped with modern decor and comfortable furnishings, catering to both holidaymakers and business travelers. Many rooms feature balconies or private terraces and offer panoramic views of the Mediterranean Sea (photo from Booking).'),
   Place(name: ' Lordos Beach Hotel & Spa', imagePath: 'larncacahotels/lordos.jpg', lat: 34.977070691954715, long: 33.690797690459775 , id: 72, category: '4 Star Hotel', city: 'Larnaca', description: 'The Lordos Beach Hotel & Spa is a distinguished 4-star hotel located in Larnaca, Cyprus. It is known for its elegant setting where land gently meets the sea, providing a warm and welcoming atmosphere. This hotel is recognized for its impeccable service and ranks among the prestigious hotels on the island, making it a popular holiday choice for many.The hotel offers various room types designed to accommodate the needs of both holidaymakers and families. Guests can enjoy sleeping on memory foam beds in rooms that feature modern classic decor, beautiful color schemes, and comfortable furnishings. The rooms come with en-suite bathrooms adorned with marble, glass, and elegant fixtures, as well as spacious balconies. Types of rooms available include the Classic Side Sea View Room, Superior Side Sea View Room, Premium Superior Side Sea View Room, Family Room, Family Suite, Junior Family Suites Side Sea View Room, Front Sea View Room, Junior Suite Sea View with Private Jacuzzi, Panoramic Suite, and the Grand Suite (photo from Booking).'),
    Place(name: 'Lebay Beach Hotel', imagePath: 'larncacahotels/lebay.jpg', lat:34.9668767791542,long: 33.66739322117476 , id: 73, city: 'Dhekelia, Larnaca', category: '4 Star Hotel', description: 'The Lebay Beach Hotel, located in Larnaca, Cyprus, offers an elegant beachfront experience with a contemporary touch. It\'s positioned on the edge of a unique twin bay, about 10 minutes\' drive from Larnaca town center and 15 minutes from the Larnaca International Airport. The hotel is known for its modern architecture and minimalist design, coupled with a long-stretched sandy beach.Guests at the Lebay Beach Hotel can enjoy various amenities, including free parking, an outdoor pool, a fitness center, free breakfast, beach access, and airport transportation. The hotel also offers conference facilities, a bar, a lounge, and a restaurant. Room features include soundproof rooms with air conditioning, room service, minibars, flatscreen TVs, and en-suite bathrooms (photo from Booking).'),
    Place(name: 'Rise Street Art Hotel', imagePath: 'larncacahotels/art.jpg', lat: 34.91818515682225, long: 33.633538538906976, id: 74, category: '3 Star Hotel', city: 'Larnaca', description: 'The Rise Street Art Hotel in Larnaca is an innovative hotel inspired by extraordinary art and influential people. Located in the heart of Larnaca, it aims to provide a unique and memorable stay. The hotel showcases a remarkable artistic experience, with each room featuring unique wall art created using various techniques. It\'s close to the famous Phoinikoudes Beach and offers modernly decorated rooms and suites with free WiFi. Amenities include a coffee/bar lounge, outdoor terrace, breakfast buffet, fitness gym, and an upcoming rooftop bar (photo from Booking).')
    ,Place(name: 'Frangiorgio Hotel', imagePath: 'larncacahotels/fara.jpg', lat:34.91841074053968, long:33.62009056774177, id: 75, city: 'Larnaca', description: 'The Frangiorgio Hotel in Larnaca, Cyprus, is a modern establishment located just 100 meters from the famous Finikoudes beach. Situated in the city center on Gregoriou Afxentiou Avenue, the hotel is only a 10-minute drive from Larnaca International Airport and 400 meters from St Lazaros Church. The hotel offers various types of rooms including Standard Double Rooms, Superior Double/Twin Rooms with City View, Double/Twin Rooms with Disability Access, Family Rooms, and Suites with Balcony. All rooms are air-conditioned and equipped with modern amenities like coffee facilities, minibars, and bathrooms with slippers and bathrobes. Guests can enjoy facilities such as free WiFi, daily housekeeping, a swimming pool, luggage storage, family rooms, and an airport shuttle service (photo from Booking)', category: '3 Star Hotel' , ),

  ];




  List<Place> getHotel (String city) {
    if (city == 'Nicosia') {
      return nicosiaHotels;
    }
    else if (city == 'Limassol') {
      return limassolHotels;
    } else if (city == 'Famagusta') {
      return famagustaHotels;
    } else if (city == 'Paphos') {
      return paphosHotels;
    } else if (city == 'Larnaca') {
      return larnacaHotels;
    }
    else {
      return nicosiaHotels;
  }}


}

