import 'package:tourismappofficial/Places/place.dart';

class Nightlife {

  List<Place> famagustaNight = [
    Place(name: 'Senior Frog\'s Party Bar', imagePath: 'FamagustaNight/senior.jpg', lat: 34.989955465542714, long:33.995132749974246, id:76, city: 'Ayia Napa, Famagusta',description: 'Senor Frogs in Ayia Napa is renowned for its vibrant party atmosphere and engaging entertainment. This lively bar offers a mix of karaoke, live comedy, and various fun activities, attracting large crowds every night during the summer season. It typically opens around 7pm and remains active until the early hours. The bar operates from March through to November and is situated on the main strip in Ayia Napa, Ayias Mavris.Visitors to Senor Frogs often describe it as one of the best bars in Ayia Napa, praising its excellent music, friendly staff, and affordable drink prices. The venue is popular among both families and friends, with staff going out of their way to create an enjoyable experience for all ages. The bar is known for its lively shows, which include dancing and other entertaining performances (photo from Tripadvisor).', category:'Night Club'),
    Place(name: 'Castle Club', imagePath: 'FamagustaNight/castle.jpg', lat: 34.989936607001134, long:33.99817411560688, category: 'Night Club', id: 77, city: 'Ayia Napa, Famagusta', description: 'The Castle Club in Ayia Napa, Cyprus, is a renowned nightclub that has been a significant part of Cyprus\'s nightlife since its inception in March 1988. It has earned recognition for its dynamic presence in the nightlife scene, racking up six DJ Mag top 100 club awards. The club features 14 bars and is known for hosting up to 20 international artists across three unique dance arenas, along with Ayia Napa\'s largest outdoor terrace and a luxury VIP area. With its immense presence and constant innovation, the Castle Club has become a top destination for nightlife enthusiasts visiting Cyprus'),
    Place(name: 'Encore', imagePath: 'FamagustaNight/encore.jpg',  lat: 34.99004490681505,long: 33.99735469657903, id: 78, city: 'Ayia Napa, Famagusta', category: 'Night Club', description: 'Encore Ayia Napa is a modern and vibrant bar located in the heart of Ayia Napa, Cyprus. Known for being in one of the busiest spots in town, the bar is spacious with ample room for dancing and a stage area for various events. Encore is recognized for its dynamic atmosphere, hosting special events, occasional live bands, special guests, and a range of entertainers including dancers and fire eaters. The lively ambiance, combined with a variety of entertainment options, makes it a popular destination for nightlife enthusiasts in Ayia Napa (photo from Tripadvisor)'),
    Place(name: 'Pepper Bar', imagePath: 'FamagustaNight/peper.jpg', lat: 34.98799146109283,long: 34.00019179657903, id: 79, city: 'Ayia Napa, Famagusta', category: 'Bar', description: 'The Pepper Bar, located on Makarios Avenue in Ayia Napa, Cyprus, is a stylish and popular venue. It is situated in one of the busiest streets of Ayia Napa, surrounded by shops, bars, and restaurants, with the main square and monastery just a couple of minutes walk away. The bar is known for serving premium brand spirits, quality cocktails, and champagne. It features a stunning white theme with mood lighting, creating a sophisticated and inviting atmosphere. This bar has established itself as a go-to spot for both locals and tourists, offering a unique and enjoyable experience in the heart of Ayia Napa (photo from Tripadvisor).'),
    Place(name: 'Pirates Inn', imagePath: 'FamagustaNight/pirates.jpg', lat: 34.98982822103638, long:33.99755485424881, id: 80, category: 'Night Club', city: 'Ayia Napa Cyprus', description: 'Pirates Inn is a lively and popular bar located in the heart of Ayia Napa, Cyprus. Known for its vibrant atmosphere, the bar is open all season and offers a variety of games, entertainment, and music, including guest DJs. Each night at Pirates Inn is unique, promising a memorable experience for its patrons. The establishment\'s popularity is evident from its high ranking among nightlife options in Ayia Napa. The duration of an evening at Pirates Inn typically ranges from 1 to 2 hours, making it an ideal spot for those looking to enjoy a fun-filled night out in the town (photo from Tripadvisor)'),
    Place(name: 'Red Square Bar', imagePath: 'FamagustaNight/redsquare.jpg' , lat:34.989544222823795, long: 33.99812094745846 , id: 81, city: 'Ayia Napa, Famagusta', category: 'Night Club', description: 'The Red Square Bar in Ayia Napa, Cyprus, is a popular bar known for its extensive assortment of alcoholic and non-alcoholic beverages, as well as a wide selection of cocktails, ranging from classic to unique, branded, and author\'s creations. It is located at 41 Katalymaton in Ayia Napa and offers a vibrant atmosphere for visitors. The bar is well-regarded for its ability to cater to various tastes, making it a preferred spot for both locals and tourists. Additionally, the Red Square Bar is conveniently situated to provide easy access to other attractions and amenities in Ayia Napa (phto from Tripadvisor)'),
    Place(name: 'Ambassaden Bar', imagePath: 'FamagustaNight/ambassander.jpg', lat: 34.9899148588204, long: 33.999426838909265, id: 82, category: 'Bar', city: 'Ayia Napa, Famagusta', description: 'Ambassaden Bar, established in 1975, is a lively and energetic establishment in Ayia Napa, Cyprus. Spread across two floors, it offers an unforgettable nightlife experience with a vibrant atmosphere and a variety of exquisite cocktails. The bar\'s interior design blends traditional charm with modern sophistication, featuring low lighting, luminous chandeliers, plush leather booths, and a spacious dance floor. Located in the heart of Ayia Napa, Ambassaden Bar is known for its neon-lit entrance, happy people, smoke and bubble shows, and a dedicated crew aiming to ensure guests have a great time. The bar is highly rated for its welcoming environment, great choice of music, and happy hour selections. It is also a preferred venue for celebrations under the Mediterranean sk'),
    Place(name: 'Paddy\'s Bar ', imagePath: 'FamagustaNight/paddy-s-bar-ayia-napa.jpg', city: 'Ayia Napa, Famagusta', lat: 34.98987031401022,id:83,long:33.99641539230451, category: 'Pub/Bar', description: 'Paddy\'s Bar in Ayia Napa, Cyprus, is celebrated as the only Irish bar in town. Established in 2002, it has become a popular destination for both locals and tourists. Known for its vibrant atmosphere, the bar features live music every night, broadcasting sports live, and serving fresh beer along with classic and signature cocktails. Paddy\'s Bar is renowned for its welcoming and friendly environment, making it a must-visit spot for those seeking a lively and enjoyable night out in Ayia Napa. The bar\'s location and the diverse range of entertainment it offers contribute to its popularity as a nightlife spot')
   ,Place(name: 'NAVA Seaside', imagePath:'FamagustaNight/nava.jpg', city: 'Paralimni, Famagusta', lat: 35.029046525205224, long:34.04447699230582 , id: 84, category: 'Bar/Reastaurant', description: 'Nava Seaside is a beachfront destination that combines a lounge and restaurant experience. It is known for its diverse menu offerings including burgers, Iberico chops, steaks, pastas, risotto, sushi, and an array of mouth-watering sharing plates. The venue stands out not just for its culinary delights, but also for its entertainment offerings, with DJ-led parties and live music being a major draw.The decor of Nava Seaside is noted for its rustic furniture, industrial lighting, and a cave-like setting, creating a unique ambiance that complements its beachfront location. Overlooking the endless blue of the sea, it offers an ideal setting for enjoying lunch, dinner, or drinks (photo from TravelDailyNewsGreece & Cyprus).' ),
    Place(name: 'Bliss Bar', imagePath: 'FamagustaNight/bliss bar.jpg', lat: 35.01775435886993, long: 34.053741525382115, id: 86, city:'Protaras, Famagusta', category: 'Bar',description: 'Bliss Bar in Protaras, near Famagusta, Cyprus, is a vibrant and popular destination known for its seasonal operation, typically from Spring until Autumn. It\'s a great spot for those seeking a relaxing evening or a glamorous night out. Renowned for its DJ-led parties, Bliss Bar is a hotspot that attracts crowds, especially on weekends during the summer season. Its location is convenient, being less than a 10-minute drive from the Leonardo Crystal Cove & Spa by the Sea in Protaras. The bar offers a wide selection of wines, spirits, and fine cocktails, making it a great choice for nightlife lovers, as well as those just looking for a nice place to enjoy drinks with friends or colleagues')
    ,Place(name: 'To Antamoma Events Venue & Chill Out Bar', imagePath: 'FamagustaNight/antamoma.jpg', lat: 35.038881396516864, long:34.0367893969035, id: 85, category: 'Beach Bar', city: 'Protaras, Famagusta', description: 'Antamoma Events Venue & Chill, located at the Golden Coast Beach Hotel in Protaras, is a vibrant and colorful beach bar. It offers a relaxed atmosphere, perfect for lifting your mood with its range of hookahs, refreshing cocktails, and delicious cheese and fruit platters. Set in a tranquil, natural environment by the sea, it\'s an ideal spot for unwinding under the sun or enjoying the evening (photo from wolf.ooo).'  )
    ,Place(name: 'Kaliva On The Beach ', imagePath: 'FamagustaNight/kaliva.jpg', city: 'Ayia Napa, Famagusta', category: 'Beach Bar', id:87, lat: 34.984667447543806, long:34.006207905799634, description: 'Kaliva on the Beach is a popular beach bar and restaurant located in Ayia Napa, Cyprus. It\'s known for providing an unforgettable clubbing experience right by the Mediterranean Sea.It\'s a convenient destination for visitors staying in the area. At Kaliva on the Beach, guests can enjoy a full bar that serves a variety of fine spirits, beers, and wines. These beverages are complemented by a selection of Japanese culinary creations, adding a unique touch to the menu. The bar is also renowned for its vibrant DJ beach parties, making it a perfect spot for those looking to enjoy a lively night out by the sea.' )
    ,Place(name: 'Yianna Marie Beach Bar', imagePath: 'FamagustaNight/yannamarie.png', lat: 35.02018269419366, long: 34.05146454764222, city: 'Protaras, Famagusta', category: 'Beach Bar', description: 'Yianna Marie Beach Bar, nestled at the beginning of Sunrise Beach in Protaras, offers a unique blend of relaxation and entertainment. This beachfront establishment is known for its superb cuisine and a diverse range of refreshing cocktails. It provides a perfect setting for enjoying live music while admiring the stunning views of the sea (photo from Yianna Marie Hotel)')

  ];

  List<Place> limassolNight = [
    Place(name: '7 Seas', imagePath: 'Limassolnight/7seas.png', lat: 34.67740065733466,long: 33.04819178676165, id: 88, city: 'Limassol', category: 'Night Club', description: '7 Seas Music Club in Limassol, Cyprus, is a popular destination for those seeking a lively and unique nightlife experience. The club is known for its diverse entertainment schedule and sophisticated atmosphere. It features a range of music nights, including RnB vibes on Wednesdays, Latin Nights on Thursdays, and performances by both resident and international DJs on Fridays and Saturdays. Sundays at 7 Seas are dedicated to Greek music, starting earlier at 18:00 pm.The club\'s interior design balances contemporary style with a sense of old-school clubbing glamour, creating an environment that is both sophisticated and exhilarating. Guests can enjoy an impressive selection of specialty cocktails and a unique bar menu while dancing the night away.'),
    Place(name: 'H Gonia ', imagePath: 'Limassolnight/gonia.jpg', lat: 34.6761045673836, category: 'Bar', long:33.043671115596354, id: 89, city: 'Limassol', description: 'Gonia Saripolou in Lemesos (Limassol), Cyprus, is a notable area known for its variety of dining and entertainment options. It features various restaurants and eateries that cater to different tastes, such as Magirio-Tavernaki to Laiko, which is located at the junction of Gonia Saripolou & Kanari in Limassol​​. Additionally, Saripolou Square is surrounded by a diverse range of food and dining establishments, including taverns, lounge bars, and restaurants offering international cuisines.This area appears to be a vibrant and lively part of Limassol, offering a mix of culinary experiences and potentially a bustling nightlife, making it a popular destination for both locals and visitors (photo from Check In Cyprus).'),
  
    Place(name: 'Blue Apple', imagePath: 'Limassolnight/blue.jpg', lat: 34.67608822098983, long:33.04309812540345, id: 90,category: 'Bar/Food',description: 'Blue Apple Bar & Restaurant in Limassol is known for its modern and quality cuisine. It\'s a part of the Saripolou square and offers Mediterranean dishes prepared with fresh and healthy ingredients. The menu includes a variety of classic dishes like pasta, meat, fish, and an array of antipasti platters. The restaurant also boasts a selection of custom-made cocktails and good music, creating a vibrant atmosphere for its patrons​', city: 'Limassol'),

   Place(name: 'Guaba Beach Bar', imagePath: 'Limassolnight/guaba.jpg', lat: 34.7027084640414,id:91, long: 33.10816656936399, category: 'Beach Bar', city: 'Limassol', description: 'Guaba Beach Bar in Limassol is a vibrant and popular destination, known for its lively atmosphere and a wide range of activities and events. It offers various entertainment options such as Zumba mornings, performances by renowned DJs like Nick Warren and Nervo, and special themed parties like the UV Beach Party. The bar creates an engaging environment with its mix of music genres,Guaba Beach Bar is particularly noted for its dynamic events, which include not only musical performances but also fitness activities like Zumba, adding a unique aspect to the beach bar experience. This combination of music, dance, and fitness activities makes it a distinctive and sought-after location in Limassol for both locals and tourists.') ,
    Place(name: 'Summer Breeze Bar', imagePath: 'Limassolnight/breeze.png', lat: 34.69984277962463,id: 92, long: 33.101163354239176, city: 'Limassol', category: 'Night Club', description: 'Summer Breeze Club in Limassol, Cyprus, is a notable nightlife destination known for its vibrant summer events. It is the only club in the city that\'s just a breath away from the sea, featuring an ultra-modern black and white striped design. The club is renowned for hosting international and European events, including performances by famous Greek and international artists as well as international DJs. This makes it a popular spot for unforgettable summer nights filled with entertainment and surprises.The club is distinguished for its innovative décor, impressive lighting, and state-of-the-art audio system, which are renewed every summer season. It has also been recognized internationally for its outdoor design and originality, receiving awards in London and in the "Stoli Original Bar & Club Awards." The wide range of alcoholic beverages, creative cocktails, and champagnes offered at the bar further enhances the overall experience.')
    ,Place(name: 'Bar du Soleil', imagePath: 'Limassolnight/bardu.jpg', lat: 34.671176001510965,long: 33.04420943375937, id: 93, category: 'Bar', city: 'Limassol', description:'Bar du Soleil in Limassol is a unique bar that offers an immersive experience combining luxurious aesthetics, historical ambiance, and a diverse range of signature cocktails. The bar\'s setting in the Old Port of Limassol seamlessly blends historical elements with modern design, creating an atmosphere that is both visually striking and inviting. It\'s a place where interior design transcends simple aesthetics, offering guests a journey into a world of creativity and imagination (phto from Check In Cyprus).'),
    Place(name: 'Notes Live', imagePath: 'Limassolnight/notes.jpg', lat: 34.67361358411557, long: 33.041794511908016, id: 94, city: 'Limassol', category: 'Music Venue', description: 'Notes Live in Limassol is a prominent clubbing and music venue, known for its commitment to high-quality music and entertainment. Established in 1993, Notes Live has become a significant part of the Cypriot music scene, popular for hosting and promoting top-notch music events. It has garnered attention for its excellent service, unique atmosphere, and reasonable pricing, making it a favorite among both locals and tourists.The venue has gained recognition not just in Cyprus but also in the Greek media, being recommended as a must-visit destination in Cyprus. Notes Live is known for featuring major figures from the Greek music scene and beyond, offering a diverse range of musical experiences to its visitors (photo from Check In Cyprus).'),
    Place(name: 'Ravens Music Hall', imagePath: 'Limassolnight/ravens.jpg', lat: 34.675006629422185, long: 33.043307310064165, id: 95, city: 'Limassol', category: 'Music Venue', description: 'Ravens Music Hall in Limassol is a notable venue that offers an intimate and friendly atmosphere for live music enthusiasts. Known for showcasing some of the best bands in Cyprus, it features an excellent sound system, top acoustics, and a layout that ensures the stage is visible from any seat in the house. This makes it an ideal place for those who are passionate about live music experiences.The venue operates with table service and tends to get busy, especially on weekends. To accommodate its guests comfortably and maintain its intimate ambiance, advanced booking is recommended, which can be done via phone. Ravens Music Hall hosts a wide range of genres, making it a versatile spot for different musical tastes (photo from Tripadvisor).'),
    Place(name: 'Face Club', imagePath: 'Limassolnight/face.jpg', lat: 34.673176996209946, long: 33.04205428064289, id: 96, category: 'Night Club', city: 'Limassol', description: 'Face Club in Limassol is a nightlife spot that\'s part of the city\'s vibrant club and bar scene. It\'s known for offering a dynamic atmosphere, making it a popular choice for those looking to experience Limassol\'s nightlife. The club is usually open until the early hours of the morning, typically closing around 4:30 AM on Saturdays.While detailed information about the club\'s specific offerings, events, or unique features isn\'t readily available from the sources I accessed, Face Club\'s presence in the heart of Limassol suggests it\'s well-integrated into the local entertainment scene. Visitors to Limassol often engage in various activities like sightseeing tours, water sports, and exploring the city\'s cultural attractions. Face Club seems to fit into this diverse array of entertainment options, offering a place for both locals and tourists to enjoy the city\'s nightlife')

  ];                                                                                                                                                            

  List<Place> nicosiaNight = [
    Place(name: 'Lost+Found Drinkery', imagePath: 'nicosianight/lost.jpg', lat: 35.16655657347095, long:33.352457375126725, id: 97,category: 'Bar', city: 'Nicosia', description: 'Lost + Found Drinkery in Nicosia is a well-known bar that offers a unique and enjoyable experience for its patrons. While specific details about the bar\'s offerings, such as its menu or special events, are not readily available, it is known for its inviting atmosphere and quality service. The bar is a popular spot in Nicosia\'s nightlife, often frequented by locals and tourists alike who are looking to enjoy a relaxed and friendly environment (photo from My Cyprus Travel). '),
    Place(name: 'New Division', imagePath: 'nicosianight/new.jpg', lat:35.16738640692342, long: 33.3573250726964, id: 98, city: 'Nicosia', category: 'Bar', description: 'New Division is a well-known pub located in Nicosia, Cyprus. It offers a relaxing atmosphere combined with music, making it an ideal spot for those looking to unwind and enjoy a good time. The bar presents a selection of beers, cocktails, whiskies, and spirits. It\'s a great place to visit if you\'re in the capital and looking to experience the local pub culture (photo from CyprusNet.'),
    Place(name: 'Zonkey Bar', imagePath: 'nicosianight/zonkey.jpg', lat: 35.16769961240605, long: 33.357461019301184,id: 99, category: 'Bar', city: 'Nicosia', description: 'Zonkey Bar in Nicosia is a unique and inviting establishment that stands out for its distinct ambiance. It offers a combination of pub and bar vibes, with atmospheric lighting and a special setting that enhances the overall experience for its patrons. The bar is known for its wonderful and signature cocktails, a variety of drinks and wines, complemented by cheese and fruit platters, and tasty finger food. With mainstream music playing in the background, Zonkey Bar provides a perfect atmosphere for an enjoyable night out (photo form Check In Cyprus).' ),
    Place(name: 'Patio Cocktail Bar', lat: 35.17301739168182,long: 33.361209142603755, id: 100, imagePath: 'nicosianight/patio.jpg', city: 'Nicosia', category: 'Cocktail Bar', description: 'Patio Cocktail Bar in Nicosia is a well-regarded destination known for its unique atmosphere and diverse offerings. Established on July 17, 2013, the bar was part of the revitalization of the old city of Nicosia. It aims to transport visitors to Latin America through its specialized cocktails and tapas. The menu at Patio Cocktail Bar is crafted by Chef Thanos Stasinos and offers an exciting array of choices (photo from Check In Cyprus).')
   , Place(name: 'State Club', imagePath: 'nicosianight/state.jpg', lat: 35.16365666594088, long:33.347824676970696, id: 101, city: 'Nicosia', category: 'Night Club', description: 'State Night Club in Nicosia offers a high-class nightlife experience with an impressive audio-visual environment. Known for its world-class entertainment and service, the club is an ideal destination for a glamorous night out. With a capacity to host 800 guests, it stands out for its impressive decor and vibrant atmosphere, making it a popular choice in Nicosia\'s nightlife scene (photo from Check In Cyprus).'),
    Place(name: 'Notes and Spirits', imagePath: 'nicosianight/notesspirtis.jpg', lat: 35.16774104180961, long:33.35731515551265, id: 101,category: 'Bar', city:'Nicosia',description: 'Notes and Spirits is a distinctive bar located in Nicosia, Cyprus, known for its focus on a broad and eclectic range of music. The bar, which also operates as an independent music label, specializes in various music genres such as instrumental hip hop, trip hop, funk, breaks, dub, and electro swing. This makes it a unique destination for music enthusiasts looking for a varied auditory experience.'),
    Place(name: 'Neverland Rock Bar ', imagePath: 'nicosianight/neverland.jpg', lat:35.1709029041774, long:33.36866740434956, id: 102, category: 'Bar/Food', city: 'Nicosia', description: 'Neverland Rock Bar, a classic rock establishment, has been a vibrant part of Old Nicosia\'s nightlife since its inception in 2009. This bar is not just a place for drinks; it\'s a cultural hub for rock music enthusiasts. Open daily from 20:00 until the late hours, it offers a diverse range of weekly events including live music, vinyl record nights, and tribute events, catering to a wide spectrum of rock music tastes from the 60s to the present day.The bar\'s atmosphere is enhanced by its excellent selection of beers, whiskies, classic cocktails, and other spirits. Complementing the drinks, Neverland Rock Bar also offers a variety of food options, ranging from juicy chicken or beef burgers to delicious club sandwiches and even a vegan burger, as well as various finger food platters. This combination of great music, a wide selection of drinks, and tasty food makes it a must-visit destination for both locals and visitors in Nicosia (photo from Tripadvisor).'  )
   ,Place(name: 'Murphy\'s Pub ', imagePath: 'nicosianight/murphys.jpg', lat: 35.16297681928925, long: 33.34619607973165, id: 103, city: 'Nicosia', category: 'Pub/Food', description: 'Murphy\'s Pub in Nicosia is a well-regarded establishment that offers a blend of European and pub-style cuisine, along with vegan options. The pub is recognized for its welcoming atmosphere and is a popular choice for both locals and visitors in Nicosia. Murphy\'s Pub serves a variety of meal types including breakfast, lunch, dinner, and drinks, catering to diverse preferences and times of the day (photo from Tripadvisor).'),
    Place(name: '50\'s Resto-Bar', imagePath: 'nicosianight/50s-bar.jpg', lat: 35.17421460849815, long: 33.36355487552027, id: 104, category: 'Bar/Food', city: 'Nicosia', description: '50\'s Resto Bar is a unique and vibrant dining and drinking spot located in the heart of the old city near Phaneromenis square in Nicosia. This establishment is known for creating an atmosphere that blends party vibes with a nostalgic touch from the past. It welcomes guests to enjoy a variety of delicious food, drinks, and cocktails in a setting that harks back to the charismatic 1950s.')
  ];

  List<Place> paphosNight = [
    Place(name: 'The Wooden Pub', imagePath: 'paphosnight/wooden-pub.jpg', lat: 34.75566091150455, long:32.41405222709897, id: 105, category: 'Pub', city: 'Paphos', description:'The Wooden Pub in Paphos is a small and cozy establishment located in the center of the tourist area near the harbor. It offers a peaceful retreat that is close enough to the sea, making it an ideal spot for enjoying a drink. The pub is known for its wide selection of real ales, including seven different kinds brewed in Paphos and available in 500ml bottles. Additionally, it offers a large variety of bottled beers from around the world. Open from 10:00 AM to 12:00 AM, The Wooden Pub provides a welcoming atmosphere for its visitors (photo from Tripadvisor).'),
    Place(name: 'Loft Club', imagePath: 'paphosnight/loft.jpg',lat: 34.756716708911995, long: 32.42017606571744, id: 106, city: 'Paphos', category: 'Night Club', description: 'The Loft Club in Paphos, Cyprus, is a well-known and vibrant nightlife venue that has been a central part of the Paphos nightlife scene since its opening in 2003. This club is particularly noted for its luxurious and unlimited entertainment offerings. Located in the southern part of Paphos, near many bars and pubs, Loft Club boasts a sleek, ultra-modern interior, spread over two floors and illuminated with colorful lights.' )
   , Place(name: 'Friends Bar Paphos', imagePath: 'paphosnight/friends bar.jpg', lat: 34.75809580180865, long: 32.41663552575436, id: 107, city: 'Paphos', category: 'Bar', description: 'Friends Bar in Paphos is a popular spot for both locals and visitors. Known for its great food and vibrant entertainment, the bar offers a warm and welcoming atmosphere. It serves a variety of dishes, including tasty pizza and chicken, and is also appreciated for its selection of beers. The establishment is well-regarded for its live music performances in the evenings, contributing to a lively and enjoyable environment.'),
    Place(name: 'Rainbow Club Paphos', imagePath:'paphosnight/rainbow.jpg', lat: 34.757936833479675, long: 32.41663971559926, id: 108, city: 'Paphos', category: 'Night Club', description: 'Rainbow Club in Paphos is a notable nightlife spot, popular among locals and visitors alike. It\'s recognized for its vibrant atmosphere and is often associated with contemporary music, catering to a diverse audience. This club is one of the oldest in Paphos, marking it as a local institution in the area. Additionally, it\'s listed under both bar and night club categories, indicating a versatile setting for various evening experiences. Its location in Paphos makes it a convenient spot for those exploring the city\'s nightlife (photo from Cyprus Alive).' ),
  Place(name: 'Kleo’s Cocktail Bar & Night Club', imagePath: 'paphosnight/kleos.jpg', lat: 34.85392406991352, long:32.37743607696045, id: 109,city: 'Pegeia, Paphos', category: 'Bar & Night Club', description: 'Kleo\'s Cocktail Bar in Paphos is a well-regarded nightlife spot, known for its good atmosphere and selection of cocktails. Patrons often appreciate the bar for its welcoming ambiance and the quality of the drinks served. Its location in Coral Bay enhances its appeal, making it a central spot for visitors and locals alike who are looking to enjoy a lively evening out. The bar has garnered positive reviews from guests, who often reminisce about their experiences there. Kleo\'s Cocktail Bar is part of Papho\'s vibrant nightlife scene, ranked among the top nightlife options in the area. For those planning a visit or looking for a night out in Paphos, Kleo\'s Cocktail Bar seems to be a popular choice, especially for those interested in a cozy yet vibrant bar atmosphere (photo from Stoli & Bar Club Awards.')
 ,Place(name: 'Flinstones Bar', imagePath: 'paphosnight/fli.jpg', lat: 34.757328005552026, long: 32.416626030938644, id: 110, category: 'Bar', city: 'Paphos' , description: 'Flintstones Bar in Paphos is a popular spot for nightlife, known for its welcoming and friendly atmosphere. It stands out for its great drinks and engaging environment, making it a favorite for those who visit. The bar has earned positive reviews for its overall experience, contributing to its reputation as a must-visit destination in the area. '),
  Place(name: 'Noir Tapas & Bar', imagePath: 'paphosnight/noir.jpg', lat:34.775585936561626, long:32.42166411928823, id: 111, city: 'Paphos', category: 'Bar', description: 'Noir Tapas & Bar in Paphos is renowned for its ambiance and setting, providing a unique experience that goes beyond just food. It\'s a destination that combines a comfortable and inviting atmosphere with a selection of drinks, making it a popular spot for both socializing and relaxing. The bar\'s interior and environment are often highlighted in reviews for their appeal and contribute significantly to the overall experience of the patrons.Located in Kennedy Square, Noir Tapas & Bar is known for its friendly service and is a popular choice for both locals and tourists. The establishment is particularly appreciated for its night-time vibe, offering an ideal setting for an evening out. Whether it\'s for a casual drink or a more celebratory occasion, the bar provides a suitable and enjoyable environment (photo from Wiz-Guide)' ),
  Place(name: 'Boulevard Bistro Wine & Bar', imagePath: 'paphosnight/boulevard.jpg', lat:34.77556250998096, long:32.421393583076465, id: 112, city: 'Paphos', category: 'Wine Bar', description: 'Boulevard Bistro Wine Bar in Paphos is a charming and sophisticated spot that has become a favorite among locals and visitors. Situated in Kennedy Square, this venue is not just about wine? it\'s also about the experience. The bistro is appreciated for its inviting atmosphere, which includes snug rooms perfect for sheltering from the wind in winter or the heat in summer. It\'s described as a romantic place with an interesting design, appropriate lighting, and well-chosen music.The outdoor seating area under a canopy is particularly popular for those who enjoy dining al fresco. Inside, the cozy and stylish interior adds to the ambiance. The bistro offers a wide selection of wines, including by the glass, and the presence of a professional sommelier enhances the experience (photo from Phileas Guides).' ),
  Place(name: 'Mr Tippler', imagePath: 'paphosnight/check.jpg', lat:34.77750220912052, long: 32.42079545424175, id: 113, category: 'Bar', city: 'Paphos', description: 'Mr. Tippler is a vibrant and popular cocktail bar located in the old town of Paphos. It\'s known for its engaging atmosphere and wide array of handcrafted cocktails, making it a favorite spot for both locals and tourists. The bar has a unique history, being situated in a building from the early 20th century that was previously used for charcoal burning and later as a truck garage. The restoration of this building was a significant project, adding character to the bar\'s ambiance. The bar prides itself on offering a diverse cocktail experience, moving away from the traditional bar culture in Paphos. Their cocktail drinks program is bold, with the menu flavors changing with the seasons. This approach has made Mr. Tippler a go-to destination for fine drinking enthusiasts. Visitors to the bar can expect a jovial atmosphere, where they can enjoy drinks, dance, meet friends, or make new ones (photo from Tripadvisor).' ),
  Place(name: 'SOHO. 79 Bar', imagePath: 'paphosnight/soho.jpg', lat:34.779127429412064, long: 32.42066499229753, id: 114, city: 'Paphos', category: 'Bar/Food', description: 'Soho.79 Cocktail & Sushi Bar in Paphos is known for its luxurious ambiance and culinary excellence, offering a unique experience that goes beyond just food and drink. Established in 2020, this bar is celebrated for its mixology art and the intricate crafting of sushi. It boasts an award-winning bartender from Athens who brings creativity to each cocktail and an experienced chef specializing in Japanese cuisine. The modern and stylish space at Soho.79 is designed to complement the dining experience, fostering an atmosphere of luxury and comfort.Customers have praised Soho.79 for its exceptional food, service, and ambiance. The sushi is noted for its generous portions and taste, while the cocktails, like peachy negroni and spicy Thai, are favorites among guests. The decor of the bar is described as smart and fabulous, making it a standout place in the center of Paphos\'s old town. Despite some comments about loud music, the overall feedback highlights a vibrant and enjoyable atmosphere (photo from Check In Cyprus).' )
    ,Place(name: 'Oniro by the sea', imagePath: 'paphosnight/oniro.jpg',id: 207, lat: 34.873530996127904, long: 32.342634037732815, category: 'Beach Bar', city: 'Pegeia, Paphos', description: 'Oniro by the Sea is a popular beach bar located in Paphos, known for its stunning views overlooking the sea caves. It provides an ideal setting for enjoying cocktails in a romantic ambiance, especially during sunset. The bar offers a variety of dishes including steak sandwiches, home-made burgers, paella with mussels and prawns, and seafood risotto, catering to a wide range of tastes.')

  ];

  List<Place> larnacaNight = [
    Place(name: 'Club DEEP', imagePath: 'larnacaNight/deep.jpg', lat: 34.91374572907729, long: 33.63797693094401, id: 115, city: 'Larnaca', category: 'Night Club', description: 'Club Deep, located in Larnaca, Cyprus, is a prominent nightlife destination known for its vibrant and edgy atmosphere. Situated on the Larnaca seaside, specifically in the Finikoudes area, it offers a picturesque setting that combines the charm of a beachfront location with the excitement of a bustling nightclub.The club is renowned for its high-energy vibe and features a top-notch sound system that plays a variety of music genres, including RnB, Hip Hop, House Music, and more. It\'s a hotspot for party enthusiasts and is frequented by some of the best DJs in the city, ensuring a wild night of entertainment for its guests (photo from Phileas Guide).'),
    Place(name: 'DSTRKT', imagePath: 'larnacaNight/DSTRKT-1.jpg', lat: 34.91487802664983, long: 33.63468842113693, id: 116, city:'Larnaca', category: 'Bar/Food', description: 'DSTRKT Bar in Larnaca, Cyprus, is a popular destination that caters primarily to a young crowd. Located in the lively Ermou Square, this seafront café is known for its vibrant and energetic atmosphere. It\'s a place where visitors can enjoy a variety of drinks and fast food in a setting that is both loud and animated.The bar\'s menu includes a wide range of cocktails, along with other drinks like gin, wines, and beers. For those looking for a bite to eat, DSTRKT Bar also offers a selection of food items, including options for breakfast, brunch, main dishes, salads, kid’s meals, platters, and desserts. The bar is equipped to provide a fulfilling experience both in terms of beverages and food (photo from Check In Cyprus).'),
    Place(name: 'Ammos Beach Bar', imagePath: 'larnacaNight/ammos.jpg', lat: 34.897779773696044, long:33.613067392683966, id: 117, category: 'Beach Bar', city: 'Larnaca', description: 'Ammos Beach Bar is a picturesque and lively spot located on a sandy beach with crystal-clear waters. The bar features a relaxed, bohemian aesthetic, with an open-air structure made of natural wood and thatched roofs, providing a perfect blend of rustic charm and modern comfort. Vibrant, colorful cushions and hammocks are scattered throughout, offering cozy seating options. The bar area is adorned with strings of twinkling fairy lights, creating a warm and inviting ambiance, especially at night. Tropical plants and palm trees surround the bar, enhancing the beachside feel. (photo from Ammos) '),
    Place(name: 'Rebuke Lounge', imagePath: 'larnacaNight/rebuke.jpg', lat:34.89165067816311, category: 'Beach Bar', city:'Larnaca',long: 33.638235942958666, id: 118, description: 'Rebuke Lounge, located in Larnaca, is a trendy, sea-side restaurant known for its sushi and international cuisine. The ambiance of the place is described as chilled, with a summer vibe, featuring a modern bohemian décor with bamboo themes. It appears to offer a comfortable and aesthetically pleasing environment, suitable for both family and friends (photo from My Guide Cyprus).'),
    Place(name: 'Lush Beach Bar Resto', imagePath: 'larnacaNight/lush.jpg', lat: 34.890632278021265,id: 119, city:'Larnca', category:'Beach Bar',long: 33.6381626424489, description: 'Lush Beach Bar in Larnaca is a luxury lifestyle venue that offers a range of exceptional experiences all year round. It is known for its artisanal cocktails, live events, exquisite cuisine, and a unique atmosphere that changes with each season. The venue is designed to create memorable stories for its guests, with a focus on food, music, and cocktails enhancing the overall experience.The culinary offerings at Lush Beach Bar are a highlight, with the menu featuring a variety of dishes that cater to different tastes and dietary preferences (photo from My Guide Cyprus).')
    ,Place(name: 'Savino Rock Bar', imagePath: 'larnacaNight/savino.jpg', lat:34.912096648662484,id: 120, city:'Larnaca',category:'Bar',long: 33.63763998899567, description: 'Savino Rock Bar, established in 1990, stands as one of the oldest and most classic rock bars in Larnaca. Known for its unique atmosphere, the bar features an interior adorned with all wood, prints, and rock memorabilia, creating an authentic rock environment. The exterior includes a spacious traditional courtyard, which has been recently expanded and partly covered, often becoming a bustling spot for visitors..'),
     Place(name: 'NUSA Beach Bar', imagePath:'larnacaNight/nusa.jpg', lat: 34.898732064121724,id: 121, long: 33.639004171795285, category: 'Beach Bar',city: 'Larnaca', description: 'Nusa Beach Bar is a vibrant and picturesque beachfront destination located in Larnaca, Cyprus. It\'s described as a tropical oasis that provides a delightful escape for both locals and tourists. The bar\'s setting is known for its panoramic views and a laid-back island vibe, making it an ideal spot for relaxation and enjoying the sun (photo from Cyprus Alive).' )
  ];




  List<Place> getNight (String city) {
    if (city == 'Nicosia') {
      return nicosiaNight;
    }
    else if (city == 'Limassol') {
      return limassolNight;
    } else if (city == 'Famagusta') {
      return famagustaNight;
    } else if (city == 'Paphos') {
      return paphosNight;
    } else if (city == 'Larnaca') {
      return larnacaNight;
    }
    else {
      return nicosiaNight;
  }}


}

