import 'package:tourismappofficial/Places/place.dart';


class Restaurants {
  List<Place> famagustaRest = [
    Place(name: 'Taverna Napa', imagePath: 'famagustaRest/napa.png', id:122, lat: 34.992157456170666,long: 34.000597110416706, city: 'Ayia Napa, Famagusta', category: 'Restaurant, Traditional Food',description: 'Taverna Napa, established in 1976, is a renowned dining establishment in Ayia Napa, Cyprus, known for its exceptional cuisine and memorable dining experience. Located in a traditional Cypriot house built in 1918 at the northern entry of Ayia Napa, it offers a unique blend of local and international culinary delights.The taverna is celebrated for creating an intimate and relaxed atmosphere that appeals to both local and foreign guests. It\'s particularly noted for hosting weddings, events, and parties, providing an ideal setting for romantic and dreamlike celebrations. The ambience is enhanced by the use of traditional decorations and a beautiful fireplace, which adds to the charm during colder days. Additionally, the taverna features a vineyard outside, adding to its picturesque setting.'),
    Place(name: 'en yevo Tavernaki', imagePath: 'famagustaRest/enyevo.jpg', city:'Ayia Nappa, Famagusta',lat: 34.989353335970335, long: 34.00260441502058, id: 123, category: 'Restaurant, Traditional Food', description: 'En-Yevo Tavernaki, located in Ayia Napa, Cyprus, offers a unique and traditional dining experience, deeply rooted in Cypriot culture and cuisine. Established in a quaint and historic setting, the tavern is known for its authentic Cypriot and Greek dishes. The owners, Bambos and Christos, place a high priority on selecting fresh, local ingredients to create a delightful culinary journey for their guests (photo from CyprusAlive).'),
    Place(name: 'Glasshouse Lounge Restaurant', imagePath: 'famagustaRest/glass.jpg', lat:34.98814797107735, id:124, long: 33.96692369046032 , category: 'Restaurant, SeaFood/European', description: 'The Glasshouse Lounge Restaurant in Ayia Napa, Cyprus, is a highly-rated dining establishment located on the top floor of the Adams Beach Hotel. It overlooks Nissi and Macronissos Bays, offering guests exceptional views combined with exquisite cuisine. The restaurant specializes in seafood, international, and Mediterranean dishes, and caters to various dietary needs with options for vegetarian, vegan, and gluten-free meals. The ambiance is noted for its combination of fine dining with a welcoming atmosphere, making it suitable for special occasions, romantic dinners, or just an enjoyable evening out. The Glasshouse Lounge Restaurant is particularly praised for its high-quality food, excellent service, and the unique dining experience it provides (photo from Adams Beach Hotel In Cyprus).'),
    Place(name: 'The Deck Terrace Restaurant', imagePath: 'famagustaRest/the deck.jpg', lat: 34.984654974828885,id: 125, long: 34.01156533647862, category: 'Restaurant, Seafood/European', city: 'Ayia Napa, Famagusta', description: 'The Deck Terrace Restaurant, situated in Ayia Napa, Cyprus, is a renowned dining destination known for its al fresco dining experience under the starry sky. It is part of the Alion Beach Hotel and offers a menu filled with à la carte Mediterranean delights and gourmet dishes, enhanced by the soothing sounds of waves. The restaurant\'s intimate setting makes it an ideal spot for romantic dinners and special occasions. It has garnered high praise for its excellent food and service, with a menu that includes a range of Mediterranean, seafood, European, and Central European cuisines. The restaurant is also accommodating to various dietary needs, offering vegetarian, vegan, and gluten-free options (photo from Tripadvisor).'),
    Place(name: 'Sage Restaurant & Wine Bar', imagePath: 'famagustaRest/sage.jpg', lat: 34.988304009806356,id: 126, category: 'Restaurant, European',long:34.00182854628587, city: 'Ayia Napa, Famagusta', description: 'Sage Restaurant & Wine Bar in Ayia Napa, Cyprus, is a highly-rated dining destination known for its international, Mediterranean, and European cuisine. The restaurant offers an array of dishes that cater to various tastes, including seafood and a variety of gourmet options. It is praised for its excellent service and the quality of food, providing an upscale dining experience. The atmosphere at Sage Restaurant & Wine Bar is perfect for a fine dining experience, making it a popular choice for both locals and tourists. ')
    ,Place(name: 'Flames Reastaurant and Bar', imagePath: 'famagustaRest/flames.jpg', lat: 34.98896560866961, long: 33.98697801502042, id:127, city: 'Ayia Napa, Famagusta', category: 'Restaurant, General/Bar', description: 'Flames Restaurant and Bar in Ayia Napa, Cyprus, is a popular dining destination known for its mix of traditional Cypriot and international cuisine. Established in 1989 as a family business, the restaurant is run by Theo, a trained chef, and his brother Peter, a trained waiter. It ranks among the top 20 restaurants in Ayia Napa on TripAdvisor, thanks to its combination of friendly staff, great atmosphere, and delicious food. The menu features steak, fish, and vegetarian specialties, complemented by a carefully selected wine list and homemade desserts. Open daily, Flames Restaurant and Bar promises an intimate and relaxed dining experience, making it a memorable stop for both local and foreign patrons (photo from Tripadvisor)'),
    Place(name: 'The Agrotikon Restaurant & Bar', imagePath: 'famagustaRest/agrotikon.jpg', lat: 34.98826035059448, long: 33.95387913647873, id: 128,  description: 'The Agrotikon Restaurant & Bar, located in Ayia Napa, Cyprus, is renowned for its authentic Cypriot cuisine. They take pride in the quality of their meals, offering original Cypriot recipes like Mousaka, Stifado, and Kleftiko, as well as an extensive selection of meat and fish meze. The restaurant emphasizes using only fresh ingredients, with fish sourced from Cyprus and the finest oils for cooking. Their menu is quite extensive, featuring over 22 starters, a variety of pasta, salads, pizza, omelets, and more than 39 meat and fish main dishes, including Cypriot desserts', category: 'Restaurant, Traditional Food', city: 'Ayia Napa, Famagusta')
    ,Place(name: 'Zorbas Bakery Agia Napa', imagePath: 'famagustaRest/zorpas.jpg', lat:34.988232214707814, long: 33.968437965685816, id: 129, category: 'Bakery', city: 'Ayia Napa, Famagusta', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals (photo from Tripadvisor).' )
     ,Place(name: 'McDonald\'s Ayia Napa', imagePath: 'famagustaRest/mcdonalds.jpg', lat: 34.98644495766906, long: 33.998812183756655, id: 130, city: 'Ayia Napa, Famagusta', category: 'Fast Food', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Tripadvisor).'),
    Place(name: 'Zorbas by the sea', imagePath: 'famagustaRest/bythesea.jpg', lat:35.01364549865347, long: 34.05660094852616, id: 131, category: 'Bakery/Food', city: 'Protaras, Famagusta', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals (photo from Best Cool)' ),
    Place(name: 'McDonald\'s Protaras', imagePath: 'famagustaRest/mcpro.jpg', lat: 35.01800073201951, long: 34.047467262017136, id: 132, city: 'Protaras, Famagusta', category: 'Fast Food', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Go Dairy Free)')
    ,Place(name: 'Molti Restaurant', imagePath: 'famagustaRest/molti-restaurant.jpg', lat: 35.01317217712085, long: 34.05551685830811, id: 133, category:'Reastaurant, Seafood/European', city: 'Protaras, Famagusta',description: 'Guests at Molti Restaurant have consistently praised the quality of food, particularly highlighting dishes like steak, kleftiko, pizza, and lamb chops. The restaurant is also noted for its generous portion sizes and excellent value for money. The staff at Molti is commended for their friendly and attentive service, contributing to a welcoming and enjoyable dining experience. This makes Molti an ideal choice for various occasions, including birthday parties, bachelor parties, business meetings, and weddings (photo from e-table).')
     ,Place(name: 'Yianna Marie Restaurant', imagePath: 'famagustaRest/yianna.jpg', lat:35.02035571440687,category:'Restaurant, Seafood', long: 34.05036188369066, id: 134, city: 'Protaras, Famagusta', description: 'Located in the heart of Protaras, Yanna Marine Restaurant is a gem for seafood lovers. This establishment is celebrated for its exquisite menu, which features a rich array of seafood delicacies. Imagine savoring the freshest catch against the backdrop of Protaras\'s serene coastal ambiance. The restaurant\'s chefs skillfully combine traditional cooking methods with contemporary flavors, creating dishes that are both familiar and exciting (photo from djsprofessional).')
  ];

  List<Place> limassolRest = [
    Place(name: 'Wagamama', imagePath: 'limassolRest/wagamama-limassol.jpg', lat: 34.669615574753365, long: 33.04074050247851, id: 135, city: 'Limassol', category: 'Restaurant, Asian Food', description: 'Wagamama is a popular restaurant chain known for its pan-Asian cuisine. Originating in the UK, it has expanded globally, offering a variety of dishes inspired by the flavors of Japan and other Asian countries. The menu typically includes ramen, teppanyaki, curries, and donburi, along with an assortment of appetizers and sides. Wagamama is also known for its contemporary and minimalist interior design, adding to the dining experience. The restaurant focuses on fresh ingredients and bold flavors, making it a favorite for those seeking a casual yet vibrant dining experience with an Asian twist.'),
    Place(name: 'Remezzo CafeResto', imagePath: 'limassolRest/remezzo.jpg', lat: 34.67086381067584, long: 33.04267792756996, id: 136, category: 'Restaurant/Cafe', city: 'Limassol', description: 'Remezzo Caferesto in Limassol City is a highly regarded cafe that offers a wide range of cuisines, including vegetarian and vegan options. It\'s known for its great atmosphere and quality service. With a diverse menu that caters to various dietary needs, Remezzo Caferesto provides a delightful dining experience in a scenic location, overlooking the Old Port of Limassol. The restaurant is appreciated for its tasty dishes and has received numerous positive reviews for both its food and service. It\'s a popular spot among both locals and tourists, ideal for enjoying a meal while taking in the beautiful views of Limassol Marina (photo from Booking).'),
    Place(name: 'Jimmy\'s Killer Prawns', imagePath: 'limassolRest/jimmys.jpg', lat: 34.69635169386177, long: 33.090754157788005, id: 137, city: 'Limassol', category: 'Restaurant, Seafood', description: 'Dive into the world of seafood at Jimmy\'s Killer Prawns, a restaurant chain celebrated for its prawn-focused menu. With a diverse range of dishes, this eatery caters to seafood lovers, promising large portions and a friendly atmosphere. Customers often rave about the prawn platter, noting it as a must-try for its freshness and generous serving size (photo from Cyprus Alive).'),
    Place(name: 'Thymari, Molos', imagePath: 'limassolRest/thymari.jpg', lat: 34.671539189694094, long: 33.04290368401392, id: 138, city: 'Limassol',category: 'Restaurant, Greek Food', description: 'Thymari, located in Limassol, is a unique dining establishment that offers a delightful blend of European and Greek cuisines with a special emphasis on grilled dishes. The restaurant is designed to cater to a variety of tastes, including those seeking healthier dining options. Known for its diverse menu, Thymari presents an array of choices from classic Greek dishes to contemporary European fare, all centered around high-quality, grilled ingredients (photo from About Limassol).')
   ,Place(name: 'Columbia Plaza', imagePath: 'limassolRest/colubia-plaza-12.jpg', city: 'Limassol', lat: 34.67716236107006, long: 33.048047095316704, id: 139, category: 'Restaurant, European Food', description: 'Columbia Plaza in Limassol, Cyprus, is a prominent and multifaceted establishment that stands out as a significant center for both entertainment and dining. Established in November 2008, it has rapidly become a key player in the Cypriot market, catering to a diverse range of needs and preferences.')
   ,Place(name: 'TGI Fridays - Limassol Marina', imagePath: 'limassolRest/tgi-fridays-limassol.jpg',id: 140, lat: 34.668834836655954, long: 33.040914657340196, city: 'Limassol', category: 'Restaurant, European', description: 'TGI Fridays at Limassol Marina is a popular dining destination known for its American cuisine and bar options. It\'s a great place for both lunch and dinner, offering vegetarian-friendly, vegan, and gluten-free options. The restaurant enjoys a waterfront location at Limassol Marina, providing a scenic view for diners (photo from Tripadvisor).'),
    Place(name: 'Limassol Agora', imagePath: 'limassolRest/agora.jpg', lat: 34.67614789051199, long: 33.04318168307329, category: 'Restaurants', city: 'Limassol', id: 141, description: 'Limassol Agora is a vibrant and multifunctional hub located in the heart of Limassol\'s Old Town, Cyprus. It\'s a contemporary project designed to recreate the bustling atmosphere of the historical "old Pantopolio" municipal market, combining tradition with modernity. Agora has emerged as a popular destination for both locals and tourists, offering an array of experiences.'),
    Place(name: 'McDonald\'s Limassol Old Port', imagePath: 'limassolRest/mcdonalds-old-port.jpg', lat: 34.6711590339321,long: 33.04287107879868, id:142, city: 'Limassol', category: 'Fast Food', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Tripadvisor).',)
  , Place(name: 'McDonald\'s Limassol Germasogia',lat: 34.70040689985333, long: 33.10107242247709, imagePath: 'limassolRest/mcgermassogia.jpg', id: 143, city: 'Limassol', category: 'Fast Food', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Tripadvisor).' )
    ,Place(name: 'Meze Taverna Restaurant', imagePath: 'limassolRest/meze.jpg', lat: 34.67671424313375, long: 33.048214957340434, city: 'Limassol', id: 144,category: 'Restaurant, Traditional Food', description: 'Meze Taverna Restaurant, located near the Old Port in Limassol, Cyprus, is a family-run establishment renowned for its traditional Cypriot and Greek cuisine. Owned by Diomides and Kicoulla Machlouzarides, who have over 30 years of experience in the restaurant industry, the eatery offers a variety of both meat and fish mezes. Among the popular dishes served are chicken breast skewers, pork kebabs, sheftalia (a homemade sausage), mixed grills, pork chops, and lamb cutlets, all accompanied by rice or chips and a garnish salad (photo from Tripadvisor).'),

  ];

  List<Place> nicosiaRest = [
    Place(name: 'Piatsa Gourounaki', imagePath: 'nicosiaRest/piatsa.jpg', lat: 35.17289966096291, long: 33.36290737855608, id: 145, category: 'Restaurant, Greek Food', city: 'Nicosia', description: 'Piatsa Gourounaki in Nicosia is a restaurant known for its Greek and Mediterranean cuisine. It is located on Faneromenis Street. The menu includes a variety of options such as doner kebabs, souvlakia, and meat platters. The restaurant is appreciated for its local cuisine and offers options for different dietary preferences, including vegetarian, vegan, and gluten-free choices. For more specific details and reviews, you might want to visit their website or check out travel review sites like TripAdvisor.'),
    Place(name: 'Zanettos', imagePath: 'nicosiaRest/zanettoo.jpg', lat: 35.17296527156222, long: 33.36504773279669, id: 146, city: 'Nicosia', category: 'Restaurant, Traditional Food', description: 'Zanettos, located in the old town centre of Nicosia on Trikoupi Street, is a traditional Cyprus taverna that has been a significant part of the area\'s culinary landscape since 1938. The taverna, founded by Savvas Zanettos, is renowned for its commitment to high-quality and caring service, a tradition that has been maintained since its inception.'),
    Place(name: 'Pyxida', imagePath: 'nicosiaRest/Pyxida-Nicosia.jpg', lat:35.166974072705415, long: 33.357297703961564, id: 147, city: 'Nicosia', category: 'Restaurant, Seafood', description: 'Pyxida Fish Tavern in Nicosia is a renowned seafood restaurant that has been providing high-quality seafood since 2004. The founders of the restaurant are Giannos Christoforou and Petros Georgiou. The establishment is known for its commitment to serving the freshest ingredients, combined with discrete service to ensure a great dining experience for guests. Their menu features a variety of signature dishes, primarily focused on seafood, and the restaurant is noted for its elegant atmosphere (photo from in-Cyprus).'),
   Place(name: 'Mezostrati Tavern', imagePath: 'nicosiaRest/mezostrati.jpg', lat:35.16889411726716, long: 33.35843582541994, id: 148, city: 'Nicosia',category: 'Restaurant, Traditional Food', description: 'Mezostrati Tavern in Nicosia is a popular dining spot known for its traditional and homemade style cuisine. The menu at Mezostrati features a variety of options catering to different tastes and preferences, suitable for any time of the day or night. They offer services such as delivery and take-away, alongside the option to dine in, particularly during their special royal evenings. The menu changes daily, ensuring a fresh and varied dining experience for regular patron(photo from Tripadvisor)' ),
   Place(name: 'Kathodon', imagePath: 'nicosiaRest/kathodon.jpg', lat: 35.174233600943026, long: 33.36124051008063, id: 149, city: 'Nicosia', category: 'Restaurant, Greek Food', description: 'Kathodon in Nicosia is a Greek restaurant known for its vast and creative menu, blending elements from both Greek and Turkish cuisines. It\'s particularly famous for dishes like stuffed Florina pepper, Smyrne meatballs (soutzoukakia) in tomato sauce, kleftiko (slow-baked lamb marinated in garlic and lemon juice), and shish kebab giaourtlou served with a garlicky yogurt dressing. For dessert, the samali with Aegina pistachios, a popular dish in Greece and Cyprus, is a recommended choice (photo from Tripadvisor)'),
    Place(name: 'The Gym', imagePath: 'nicosiaRest/thegym.jpg', lat:35.17282075603566, long: 33.36292251264767, id: 150, category: 'Restaurant, European Food', city: 'Nicosia', description: 'The Gym in Nicosia is a trendy and popular venue, particularly favored by a younger and fashionable crowd. Located in the central Onasagorou area, it\'s a place that combines aesthetic appeal with delicious food. The venue is covered in ivy leaves, adding to its charm and ambiance (photo from Tripadvisor).' ),
    Place(name: 'Moondog\'s Bar & Gril', imagePath: 'nicosiaRest/moon.jpg', lat:35.16470913518642, long: 33.36117758065907, id: 151, city: 'Nicosia', category: 'Pub/Food' , description: 'Moondog\'s Bar & Grill in Nicosia is a popular destination that combines great food, music, and sports in a vibrant atmosphere. Established with a mission to cater to people who appreciate good music, enjoy sports, and love sharing moments with friends and family, Moondog\'s offers an environment with a rock attitude and a serious approach to burgers and beers.')
  ];

  List<Place> paphosRest = [
    
    Place(name: 'Kings Restaurant', imagePath: 'paphosrest/king.jpg', lat: 34.75828227050722, long: 32.411856642562256, id: 152, city: 'Paphos', category: 'Restaurant, Seafood', description: 'King\'s Restaurant in Paphos is a well-established dining venue located in the heart of Paphos Harbour. Open since 1972, this restaurant has become a prominent fixture in the area, known for its breathtaking views from the terrace, overlooking the harbour and the Mediterranean Sea. It\'s situated close to the ancient Castle and the archaeological Park, making it an ideal spot for those seeking both a scenic dining experience and a touch of historical ambiance (photo from Tripadvisor).'),
    Place(name: 'Windmill Restaurant', imagePath: 'paphosrest/win.jpg', lat:34.759606403489286, long: 32.41450841674087, id: 153, city: 'Paphos', category: 'Restaurant, Traditional Food', description: 'Windmill Restaurant, located in Paphos, Cyprus, is known for its inviting atmosphere and excellent culinary offerings. It\'s a family-run establishment that has been receiving positive feedback from visitors. The restaurant\'s menu features a mix of Cypriot, Greek, and international dishes, with a particular focus on local cuisine (photo from Tripadvisor).' ),
    Place(name: 'Laona Restaurant', imagePath: 'paphosrest/laona.jpg', lat: 34.77818809454787, long: 32.420419303948805, id: 154, category: 'Restaurant, Traditional Food', city: 'Votsi, Paphos', description: 'Laona Restaurant in Paphos is a highly regarded establishment known for its traditional Cypriot and Mediterranean cuisine. Established in 1986 and still under the same management, it has gained a reputation for serving home-cooked meals that are both delicious and reasonably priced (photo from Foursquare)'),
    Place(name: 'Santa Marina Fish and chips', imagePath: 'paphosrest/santa-marina.jpg', lat: 34.853844572870976,long: 32.37879368123489, id: 155, city: 'Pegeia, Paphos', category: 'Reastaurant, Seafood', description: 'Santa Marina Fish and Chips in Paphos is a well-regarded seafood and European cuisine restaurant, known for its high-quality dishes. It is particularly celebrated for its fish and chips, but the menu also includes a variety of other options. The restaurant has received a Travelers\' Choice award from Tripadvisor, indicating consistent high praise from customers. It\'s located on Coral Bay Main Road in Paphos and is recognized for its excellent food, service, value, and atmosphere (photo from Tripadvisor).' ),
    Place(name: 'Karlina', imagePath: 'paphosrest/karlina.jpg', lat:34.77500457079933, long: 32.409221022192064, id: 156, city: 'Paphos', category: 'Restaurant, European Food', description: 'Karlina Restaurant in Paphos is a family-run establishment well-known for its wide range of fresh, locally sourced food, including local and international dishes. The restaurant has received the Travellers\' Choice award for 2023, highlighting its popularity and quality. Located opposite the World Heritage Site Tombs of the Kings, Karlina offers a unique dining experience with live music and performances every Friday night. The menu includes set menus, meze, and fish meze, catering to various tastes and preferences. The restaurant is open from morning to late at night, making it a convenient choice for any meal. ')
     ,Place(name: 'McDonald\'s', imagePath: 'paphosrest/paphos-mcdonalds.jpg', lat: 34.77044654560895, long: 32.41140950433385, id: 157, category: 'Fast Food', city: 'Paphos', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Tripadvisor).')
    ,Place(name: 'McDonald\'s, Dimokratias', imagePath: 'paphosrest/mc2paphos.jpg', lat: 34.77753918343476, long: 32.44227806721506, id: 158, category: 'Fast Food', city: 'Paphos', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Tripadvisor).')
    ,Place(name: 'Zorbas, Kato Paphos', imagePath: 'paphosrest/zofda.jpg', lat:34.76121035792001, long: 32.41575375784039, id: 159, category: 'Bakery/Food', city: 'Paphos', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals (photo from Tripadvisor).' )
    ,Place(name: 'Zorbas, Agios Theodoros', imagePath: 'paphosrest/zo2.jpg', lat:34.77119036903724, long: 32.41919098235357, id: 160, category: 'Bakery/Food', city: 'Paphos', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Zorbas, Geroskipou', imagePath: 'paphosrest/zorpas3.jpg', lat:34.76562456762179, long: 32.453948640294286, id: 161, category: 'Bakery/Food', city: 'Geroskipou, Paphos', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Zorbas, Chloraka', imagePath: 'paphosrest/zorpas4.jpg', lat:34.78626965666216, long: 32.423133427240245, id: 162, category: 'Bakery/Food', city: 'Chloraka, Paphos', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Zorbas, Leoforos Ellados', imagePath: 'paphosrest/5.jpg', lat:34.789545008111055, long: 32.43661912526196, id: 163, category: 'Bakery/Food', city: 'Paphos', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Zorbas, Eleftheriou Venizelou', imagePath: 'paphosrest/zorpass.jpg', lat:34.78356117587315, long: 32.44398226294119, id: 164, category: 'Bakery/Food', city: 'Paphos', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Jayanta Indian Restaurant',imagePath: 'paphosrest/jayanta.jpg', lat:34.75736970027435, long: 32.416092683075824, city: 'Paphos', category:'Indian Food',description: 'Jayanta Indian Restaurant is a highly rated dining establishment located in Paphos, Cyprus. It has garnered a reputation for its delicious Indian cuisine, offering a wide range of dishes including Halal, vegetarian, vegan, and gluten-free options. The restaurant has been awarded the Travellers\' Choice 2023 by Tripadvisor, indicating its exceptional quality and popularity among diners. It ranks #7 out of 496 restaurants in Paphos and has an impressive average rating of 4.5 based on over 2,300 reviews (photo from Tripadvisor)' )
  ];

  List<Place> larnacaRest = [
    Place(name: 'To Kazani Traditional Tavern', imagePath: 'larnacaRest/kazani.jpg', lat: 34.953526379260424, long:33.59578306382475, id: 165, city: 'Aradippou, Larnaca', category: 'Restaurant, Traditional Food', description: 'To Kazani Traditional Tavern is a family-run establishment located in Aradippou, a subdistrict of Larnaca, Cyprus. It offers an authentic dining experience, reminiscent of olden-day Cyprus. The restaurant is housed in a historical building, once a Zivania distillery, and its name translates to ‘the cauldron’ in reference to this past. The interiors are intimate, creating a homely atmosphere, and the service is warm and familiar (photo from in-Cyprus).'),
    Place(name: 'Maqam Al Sultan', imagePath: 'larnacaRest/maqam.jpg', lat:34.91168251808686,long: 33.6382891955073, id: 166, category: 'Restaurant, Lebanese', city: 'Larnaca', description: 'Maqam Al Sultan is a renowned Lebanese restaurant located in Larnaca, Cyprus. It\'s celebrated for offering an authentic Mediterranean dining experience, characterized by a variety of heart-healthy ingredients like fresh vegetables, grains, herbs, spices, meats, and olive oil, which are central to Lebanese cuisine. The restaurant\'s menu is designed to reflect the robust and earthy flavors typical of this region.' ),
    Place(name: 'San Pedro Street Food', imagePath: 'larnacaRest/san.jpg', lat:34.93097049265907,long: 33.617055603645966 , id: 167, city: 'Larnaca' , category: 'Restaurant, Burgers', description: 'San Pedro Street Food, located in Larnaca, Cyprus, is a popular destination for burger enthusiasts. The restaurant is highly regarded for its diverse range of burgers and is known for its fresh, quality ingredients and large portions. Some of the unique burger options available include the Texas BBQ Burger, Campfire Burger, and a variety of chicken fillet burgers. They also cater to vegan customers with options like the Beyond Burger and plant-based tenders (photo from wiz-cyprus guide).')
   , Place(name: 'Food Park City', imagePath: 'larnacaRest/foodmakenzy.jpg', lat: 34.89010677774873, long: 33.63774055019713, id: 168, category: 'Restaurant/Cafe', city: 'Makenzy, Larnaca', description: 'Food Park City in Cyprus offers a unique dining experience with locations in both Nicosia and Larnaca. This establishment is known for its diverse menu that includes a variety of cuisines such as Street Food, American, Seafood, Mediterranean, Barbecue, Asian, Greek, Eastern European, and Armenian (photo from Tripadvisor)'),
    Place(name: 'Panos Steak House', id: 169,imagePath: 'larnacaRest/panos-steak-house.jpg', category:'Restaurant, European Food', city: 'Larnaca', lat: 34.91118703086742, long: 33.63794190417005, description: 'Panos Steak House in Larnaca, Cyprus, is a popular dining establishment known for its exceptional steak and seafood offerings. Situated on Agkyras Street, it provides a scenic dining experience with views of both the sea and the Larnaca Medieval Castle. The restaurant has earned a strong reputation for its diverse menu, which includes a variety of cuisines such as Mediterranean, European, Greek, and International dishes.')
   , Place(name: 'Aldente Cucina Italiana', imagePath: 'larnacaRest/alcund.jpg', lat: 34.91345905361996, long: 33.63805678715839, id: 170, city: 'Larnaca', category: 'Restaurant, Italian Food', description: 'Aldente Cucina Italiana is a well-known Italian restaurant located in Larnaca, Cyprus. It offers authentic Italian cuisine, including a variety of pizzas and Mediterranean dishes. The restaurant is situated on Athenon Avenue in the Phinikoudes area of Larnaca, making it easily accessible for visitors. Known for its quality food and good service, Aldente Cucina Italiana is a popular choice among both locals and tourists.'),
  Place(name: 'McDonald\'s Finikoudes',lat: 34.91377222247852, long: 33.6380884501711, imagePath: 'larnacaRest/mcfinik.jpg', id: 171, city: 'Larnaca', category: 'Fast Food', description: 'McDonald\'s Corporation, an iconic American fast-food chain, was founded in 1940 as a restaurant by Richard and Maurice McDonald in San Bernardino, California, and later transformed into a franchise with the now-famous Golden Arches logo by Ray Kroc in 1955. Headquartered in Chicago, Illinois, it is one of the world\'s largest chains of fast food restaurants, operating over 40,000 locations in more than 100 countries. Renowned for its hamburgers, chicken, french fries, and breakfast items, McDonald\'s is also a significant real estate company, owning or leasing the land for its franchised location (photo from Tripadvisor).' )
    ,Place(name: 'Zorbas, Zakynthou', imagePath: 'larnacaRest/zorpas1.jpg', lat: 34.927454343749105, long: 33.63774933193953, id: 172, category: 'Bakery/Food', city: 'Larnaca', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Zorbas, Arxiepiskopou Makariou', imagePath: 'larnacaRest/zorpas2.jpg', lat: 34.92264127648379, long: 33.63857555187621, id: 173, category: 'Bakery/Food', city: 'Larnaca', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
    ,Place(name: 'Zorbas, Grigori Afxentiou', imagePath: 'larnacaRest/zorbas3.jpg', lat: 34.917827319434835, long: 33.63016916428718, id: 174, category: 'Bakery/Food', city: 'Larnaca', description: 'Zorbas Bakeries is a renowned bakery chain in Cyprus, known for its rich history and wide array of offerings. The company started about 50 years ago as a small family bakery and has since expanded to multiple locations across Cyprus. They focus on providing quality choices with high nutritional value and superior taste, emphasizing craftsmanship and tradition in their baking methods.Zorbas offers a variety of products, including bakery items, confectioneries, a selection of foods, and juices. They are particularly famous for their slow-fermented bread, known for its rich texture and thin, crispy crust. Their menu also includes warm dishes like rotisserie chicken, peas in tomato sauce, salads, sandwiches, and yoghurt meals.' )
  ];




  List<Place> getRestoraunt(String city) {
    if (city == 'Nicosia') {
      return nicosiaRest;
    }
    else if (city == 'Limassol') {
      return limassolRest;
    } else if (city == 'Famagusta') {
      return famagustaRest;
    } else if (city == 'Paphos') {
      return paphosRest;
    } else if (city == 'Larnaca') {
      return larnacaRest;
    }
    else {
      return nicosiaRest; }
  }


}

