import 'package:tourismappofficial/Places/place.dart';

class Shops {
List<Place> famagustaShops = [
  Place(name: 'Plaza Shopping Center',url: 'https://www.cyprusalive.com/en/town/plaza-shopping-center', imagePath: 'famagustaShops/plaza.png',id: 1105, lat: 34.98788043394007, long: 33.98852675879493, city: 'Ayia Napa, Famagusta', category: 'Shopping Centre',description: 'Located in the heart of Ayia Napa, the Plaza Shopping Center stands as a beacon of retail excellence, offering an unparalleled shopping experience to locals and tourists alike. Renowned as the largest shopping center in Ayia Napa, Plaza is a vibrant hub of activity, pulsating with energy and excitement.As you step into Plaza, you\'re greeted by a vast array of options catering to every need and desire. From trendy clothes to stylish shoes, exquisite jewelry to unique souvenirs, and delightful gifts for any occasion, Plaza boasts an impressive selection that caters to diverse tastes and preferences.Whether you\'re browsing for the latest fashion trends or searching for the perfect memento to commemorate your trip, Plaza Shopping Center promises an unforgettable shopping journey. With its extensive range of offerings, there\'s something for everyone within its inviting confines.Moreover, the hallmark of Plaza lies not just in its impressive array of merchandise but also in its exceptional customer service. The friendly and knowledgeable staff members are always on hand to assist shoppers, offering valuable advice and guidance to ensure a seamless and enjoyable shopping experience.In essence, Plaza Shopping Center isn\'t just a shopping destination; it\'s a bustling haven where shopping dreams come true and lasting memories are made. So whether you\'re treating yourself to a well-deserved splurge or hunting for the perfect gift for a loved one, Plaza is the ultimate destination for all your shopping needs in Ayia Napa (photo from Cyprus Alive).'),
 Place(name: 'London Clothing Company',imagePath: 'famagustaShops/london.png',id: 1106, lat: 34.98690194974274, long: 33.99698353379384, city: 'Ayia Napa, Famagusta', category: 'Clothes', description: 'Nestled in the heart of Ayia Napa\'s bustling streets, London Clothing Company stands as a beacon of style and sophistication, bringing a touch of British flair to this vibrant Mediterranean town. With its chic storefront and eclectic collection, this boutique is a haven for fashion enthusiasts seeking the latest trends and timeless classics alike.Step inside London Clothing Company, and you\'re immediately enveloped in an atmosphere of elegance and refinement. From the sleek modern decor to the carefully curated displays, every detail exudes a sense of effortless style and luxury.Peruse the racks adorned with an exquisite selection of clothing, each piece meticulously chosen to reflect the latest fashion trends straight from the streets of London. Whether you\'re searching for the perfect ensemble for a night out on the town or a casual yet chic look for a day of sightseeing, you\'ll find an array of options that cater to every taste and occasion (What\'s On Cyprus).', url: 'https://www.facebook.com/londonclothingcompany/'),
 Place(name: 'Y2K Boutique', lat:34.98749260535321, long: 33.994399914308396,id: 1107,imagePath: 'famagustaShops/y2k.png', city: 'Ayia Napa, Famagusta', category: 'Clothes', url: 'https://y2k.com.cy/', description: 'Nestled amidst the vibrant streets of Ayia Napa, Y2K Boutique stands as a beacon of retro-chic fashion, offering a nostalgic journey back to the iconic era of the early 2000s. With its neon-lit storefront and eclectic display, this boutique beckons fashion enthusiasts and trendsetters alike to explore its curated collection of vintage-inspired clothing.Step inside Y2K Boutique, and you\'re immediately transported to a time when low-rise jeans, crop tops, and velour tracksuits reigned supreme. The ambiance is electric, with upbeat music filling the air and colorful displays capturing the essence of early 2000s pop culture.Peruse the racks adorned with an array of clothing that pays homage to the iconic styles of the era. From bold prints and vibrant colors to playful embellishments and statement accessories, every piece exudes the unmistakable charm and attitude of Y2K fashion (What\'s On Cyprus).' )
 ,Place(name: 'Glamorous',category: 'Clothes', lat: 34.98671303465687, long: 34.000184980887596,imagePath: 'famagustaShops/glamorous.png',id: 1108, city: 'Ayia Napa, Famagusta', description: 'Situated in the heart of Ayia Napa\'s bustling fashion scene, Glamorous Ayia Napa stands as an epitome of sophistication and style, offering an exquisite selection of women\'s clothing that exudes elegance and allure. With its chic storefront and opulent displays, this boutique beckons discerning fashionistas to indulge in a world of luxury and glamour.Step inside Glamorous, and you\'re immediately enveloped in an atmosphere of refined sophistication. The ambiance is luxurious yet inviting, with soft lighting casting a warm glow on the meticulously curated collection of clothing.Peruse the racks adorned with an array of glamorous garments, each one a masterpiece of design and craftsmanship. From flowing evening gowns to tailored suits, chic separates to statement accessories, every piece is thoughtfully selected to cater to the modern woman who appreciates timeless elegance with a contemporary twist.', url: 'https://www.facebook.com/Glamorous.Clothing.Brand.AyiaNapa')
 ,Place(name: 'LEPUS Gift Shop - Ayia Napa', imagePath: 'famagustaShops/lepus.png',id: 1109,city: 'Ayia Napa, Famagusta', category: 'Accesories', url: 'https://lepus.com.cy/', lat: 34.986440721015136,long: 33.999586332096015, description: 'Nestled amidst the charming streets of Ayia Napa, Lepus Gift Shop Accessories stands as a delightful treasure trove of unique and enchanting accessories. With its inviting storefront and whimsical displays, this boutique beckons visitors to explore its curated collection of handpicked treasures, each one brimming with character and charm.Step inside Lepus Gift Shop Accessories, and you\'re greeted by an array of delights that spark the imagination and ignite the senses. From delicate jewelry pieces to stylish scarves, trendy handbags to playful trinkets, every item exudes a sense of whimsy and personality that sets it apart from the ordinary.Peruse the shelves adorned with an eclectic mix of accessories, each one a testament to the artistry and craftsmanship of its creator. Whether you\'re seeking a unique statement piece to elevate your outfit or a thoughtful gift for a loved one, Lepus Gift Shop Accessories offers a diverse range of options to suit every style and occasion (photo from Cyprus.com).'),
Place(name: 'LEPUS Gift Shop - Protaras', city: 'Protaras, Famagusta', category: 'Accesories',id: 1110, url: 'https://lepus.com.cy/', lat: 35.01729830457807, long: 34.04838957739944, description: 'Nestled amidst the charming streets of Ayia Napa, Lepus Gift Shop Accessories stands as a delightful treasure trove of unique and enchanting accessories. With its inviting storefront and whimsical displays, this boutique beckons visitors to explore its curated collection of handpicked treasures, each one brimming with character and charm.Step inside Lepus Gift Shop Accessories, and you\'re greeted by an array of delights that spark the imagination and ignite the senses. From delicate jewelry pieces to stylish scarves, trendy handbags to playful trinkets, every item exudes a sense of whimsy and personality that sets it apart from the ordinary.Peruse the shelves adorned with an eclectic mix of accessories, each one a testament to the artistry and craftsmanship of its creator. Whether you\'re seeking a unique statement piece to elevate your outfit or a thoughtful gift for a loved one, Lepus Gift Shop Accessories offers a diverse range of options to suit every style and occasion (photo from Cyprus.com).', imagePath: 'famagustaShops/lepus.png'),
Place(name: 'Pranco Boutique',imagePath: 'famagustaShops/pranco.png', city: 'Protaras, Famagusta',id: 1111, category: 'Clothes', lat: 35.01492086543959, long: 34.052240393344306, url: 'https://www.facebook.com/prancoboutique/', description: 'Nestled in the picturesque coastal town of Protaras, Pranco Boutique stands as a beacon of contemporary style and sophistication, offering an exquisite selection of clothing that epitomizes elegance and refinement. With its charming storefront and inviting ambiance, Pranco Boutique beckons fashion enthusiasts to embark on a sartorial journey filled with luxurious fabrics and timeless designs.Step inside Pranco Boutique, and you\'re greeted by a carefully curated collection of garments that seamlessly blend modern trends with classic elegance. From chic dresses to tailored separates, casual essentials to statement pieces, every item exudes a sense of effortless sophistication and impeccable craftsmanship.Peruse the racks adorned with an array of clothing, each piece meticulously chosen to cater to the discerning tastes of the modern woman. Whether you\'re dressing for a special occasion or seeking to elevate your everyday wardrobe, Pranco Boutique offers a diverse range of options to suit every style and occasion (photo from djsprofessional).')
];
List<Place> limassolShops= [
  Place(name: 'Hyper Fashion Boutique Limassol', city: 'Limassol', category: 'Clothes',id: 1112, lat:34.68635522933246, long: 33.0345637954418, url: 'https://eshop.hypercy.com/', imagePath: 'limassolShops/hyper.png', description: 'Nestled in the bustling streets of Limassol, Hyper Fashion Boutique stands as a beacon of contemporary style and trendsetting fashion, offering an exquisite selection of clothing that epitomizes elegance and sophistication. With its sleek and modern storefront, Hyper Fashion Boutique invites fashion enthusiasts to embark on a sartorial journey filled with luxurious fabrics, cutting-edge designs and timeless pieces.Step inside Hyper Fashion Boutique and you\'re greeted by an array of carefully curated garments that seamlessly blend high fashion with everyday wearability. From chic dresses to tailored separates, casual essentials to statement pieces, every item exudes a sense of effortless sophistication and impeccable craftsmanship. Peruse the racks adorned with an eclectic mix of clothing, each piece meticulously chosen to cater to the discerning tastes of the modern woman. Whether you\'re dressing for a special occasion or seeking to elevate your everyday wardrobe, Hyper Fashion Boutique offers a diverse range of options to suit every style and occasion (photo from 2BenInStore).' )
,Place(name: 'Megastores', imagePath: 'limassolShops/megastores.png',city: 'Limassol',id: 1113, category: 'Clothes', lat: 34.67673785721295, long: 33.04538775058534, url: 'https://megastorescy.com/', description:'Megastores in Limassol is a fashion-focused retailer offering a wide range of men\'s clothing and accessories. Their product lineup includes T-shirts, hoodies, sweatshirts, joggers, tracksuits, knitwear, cargo pants, jackets, shoes, shirts, vests, blazers, jeans, pants, twin sets, swimwear, shorts, and kidswear. They also offer various accessories like bracelets, earrings, necklaces, rings, belts, socks, underwear, bags, cigarette cases, headwear, cross-body bags, face masks, sunglasses, and watches.')
,Place(name: 'Classic Club',imagePath: 'limassolShops/classic.png', city: 'Limassol',id: 1114, category: 'Clothes', lat: 34.700768996273354,long: 33.102436179306714, url: 'https://www.classicclub.com.cy/', description: 'Classic Club Cyprus is a luxury multi-brand menswear boutique established in 2005, focusing on high-end Italian brands. It started with three shops in Kyiv, Ukraine, and has expanded to Cyprus, offering exclusive, high-quality men\'s wear. They prioritize customer satisfaction and loyalty, featuring products that stand out for their exclusivity, materials, and adherence to the latest elegant men\'s style trend.'),
  Place(name: 'Calestino Limassol',imagePath: 'limassolShops/calestino.png', city: 'Limassol',id: 1115, category: 'Clothes', lat: 34.67780446663259, long: 33.04489242467761, url: 'https://www.celestinofashion.com/?csource=gads_search_brand_cy&cmedium=cpc&ccampaign=Celestino_CY&gad_source=1&gclid=CjwKCAiAxaCvBhBaEiwAvsLmWB0jGEarbsTMgt3LGysI7-pZ5N1PSgynZMm-rt9lt8WBmHdrGC30aRoCZxUQAvD_BwE', description: 'Celestino Limassol stands as a distinguished name in the world of fashion, recognized for its innovative approach to blending traditional craftsmanship with modern aesthetics. Situated in the heart of Limassol, Cyprus, this boutique clothing store has quickly become a beacon for fashion enthusiasts seeking unique, high-quality garments that embody both elegance and contemporary flair (photo from BuisinessNews.gr).')
,Place(name: 'Edge Boutique', city: 'Limassol', category: 'Clothes',imagePath: 'limassolShops/edge.png',id: 1116, lat: 34.68786307164192,long: 33.066906850763985, url: 'https://edgeboutique.com.cy/', description: 'Edge Boutique in Limassol offers a luxurious shopping experience that blends fashion with luxury, catering to both women\'s and men\'s fashion needs. They provide a wide range of clothing items including blazers, coats, dresses, jeans, jackets, knitwear, and more. Accessories like bags, belts, gloves, hats, jewelry, and shoes are also available, ensuring a comprehensive shopping destination for fashion enthusiasts. The boutique takes pride in creating an unforgettable shopping journey by offering personalized services such as enjoying a glass of champagne or wine while shopping, in a comfortable and stylish setting.Located at Vashiotis Seafront, Edge Boutique stands out with its fashion-forward appeal and visually impressive setting, making it a prime destination for those seeking an endless fashion experience by the seafront. The boutique\'s commitment to offering creative suggestions, updated trends, and exceptional service for every occasion underscores its status as "the place to be" for fashion lovers in Limassol.')
,Place(name: 'LEPUS Gift Shop',imagePath:'limassolShops/lepus.png', city: 'Limassol', category: 'Souvenir Shop',id: 1117, lat:34.67425180444805, long: 33.04461639853814, url: 'https://lepus.com.cy/', description: 'LEPUS Gift Shop offers a diverse collection of well-priced gifts and fashion accessories. Their range includes watches, bags, crystal items, jewellery, belts, hats, scarves, and brands such as Elite, Colori, Casio, Wenger, and more. The original LEPUS concept dates back to 1985, with the first shop opening in Nicosia in 1988. Now, there are 16 LEPUS Gift Shops across Cyprus, making it a prominent chain for gift shopping (photo from Cyprus.com).')
,Place(name: 'H&M', imagePath: 'limassolShops/H&M.png',city: 'Limassol', category: 'Clothes', lat: 34.677562806136706, long: 33.04443270362544,id: 1118 , url: 'https://www2.hm.com/en_eur/index.html', description: 'The H&M store in Limassol is located on Anexartisias Street in the city\'s heart. This location was eagerly awaited and marks the second branch of the international chain in Cyprus. The store occupies a space of 2,400 square meters, spread over three different stories for product display and service.')
,Place(name: 'Taleta Boutique',id: 8003, imagePath: 'limassolShops/taleta.jpg', category: 'Colthes',city: 'Limassol', lat:34.675838018553485, long:33.04433266191102, url: 'https://www.facebook.com/taleta.boutique/?locale=el_GR', description: 'Taleta Boutique in Limassol is a charming and elegant boutique shop located in the heart of this vibrant coastal city. Known for its exclusive selection of high-end fashion, the boutique caters to discerning shoppers seeking unique and stylish clothing, accessories, and jewelry. The interior of Taleta Boutique is designed with a blend of modern and vintage aesthetics, featuring soft lighting, elegant displays, and a welcoming atmosphere that invites customers to browse and shop at their leisure.' )
,Place(name: 'Rare Gems Printing ',id: 4009, imagePath: 'limassolShops/pain.jpg',url: 'https://www.facebook.com/RareGemsPrinting/', category: 'Shop', city: 'Limassol', lat: 34.6818512678944, long: 32.97267573609379, description: 'Rare Gems Printing Ltd., based in Limassol, specializes in custom clothing printing, offering unique and personalized apparel solutions for both individual and corporate clients. This company prides itself on its ability to bring creative visions to life, utilizing state-of-the-art printing technology to produce high-quality, custom-designed t-shirts, hoodies, hats, and other garments. With a focus on customer satisfaction, Rare Gems Printing Ltd. works closely with clients to ensure that each piece of clothing reflects their specific style and message, making it a popular choice for those looking to make a personal or branded fashion statement in Limassol.')
];
List<Place> NicosiaShops = [
  
  Place(name: 'POW! The Shop Nicosia',id: 1119, imagePath: 'nicosiaShops/pow.png',city: 'Nicosia', category: 'Retail Shop', lat:35.16933781415197, long: 33.35985536501664, url: 'https://pow.shop/' , description: 'POW! The Shop, located in Nicosia Centre, is Cyprus’s first and only retail store specializing in pop-culture merchandise. They offer a wide range of licensed pop culture products from popular movies, TV shows, comics, and video games, including Marvel and DC Comics characters, Game of Thrones, Star Wars, and many more (photo from 2BeInStore).')
,  Place(name: 'Posh Boutique', city: 'Nicosia',id: 1120, imagePath: 'nicosiaShops/posh.png',url: 'https://poshcyprus.com/', category: 'Clothes', lat: 35.16922496203424, long: 33.35863879271728, description: 'Posh Boutique in Nicosia is a distinguished destination for those looking to find the perfect attire for weddings or significant events. It offers an extensive selection of groom suits, making it an ideal choice for the big day of a marrying man. Beyond wedding apparel, Posh Boutique also boasts a large collection of suits suitable for any notable occasion, including office wear. This caters to individuals who wear suits daily, whether as a workplace requirement or a personal style preference.The boutique\'s offerings are not limited to formal wear; they also include a variety of men\'s clothing categories such as activewear, jeans, shirts, suits, and accessories like belts, hats, and watches. This wide range of products ensures that customers can find attire for any occasion, be it casual or forma.')
,Place(name: 'ZARA', imagePath: 'nicosiaShops/zara.png',id: 1121, city: 'Nicosia', url: 'https://www.zara.com/', category: 'Clothes', lat: 35.16730392945889,long: 33.3607612247829, description: 'In Nicosia, Zara has a presence in multiple locations, offering a wide range of the latest trends in international fashion. The stores are designed to provide a special atmosphere that enhances the shopping experience, reflecting Zara\'s commitment to the tastes, wishes, and lifestyles of its customers.'),
  Place(name: 'First Boutique 360 Nicosia',city:'Nicosia',id: 1122, imagePath: 'nicosiaShops/first.png', url: 'https://firstbtq.com/', category: 'Clothes', lat: 35.16700283604048, long: 33.3612741678481, description: 'First Boutique in Nicosia, located at 360 Nicosia on Makariou Avenue, offers a premier luxury shopping experience, featuring a carefully curated selection of clothing, shoes, leather accessories, skincare products, perfumes, and colognes from some of the world\'s most sought-after designers. Established in 2012, it has become Cyprus\'s ultimate destination for high-end fashion, providing not just a wide range of products but also exceptional customer service to ensure a satisfying shopping experience both in-store and online.This boutique is known for its exclusive collections, hand-picked by professional buyers who travel to fashion capitals every season to select unique pieces that meet First Boutique\'s standards for quality, luxury, and design. They aim to exceed customer expectations, not just meet them, by offering a personalized shopping experience that includes expert styling advice and detailed product information.'),
  Place(name: 'Jango Fashions Makariou',id: 1123, imagePath: 'nicosiaShops/jango.png',city: 'Nicosia', url: 'https://www.jangofashion.com/', category: 'Clothes', lat:35.16595417969771, long: 33.36249033827996 , description: 'Jango Fashions is a prominent clothing retailer in Cyprus, with a strong presence since 1992. The brand is known for selling a wide variety of men’s and women’s clothing and shoes, including women\'s handbags. They focus on offering authentic and genuine products from leading international brands, ensuring quality and the latest trends for their customers.'),
];
List<Place> PaphosShops = [
  Place(name:'April',id: 1125,imagePath: 'paphosShop/april.png', url: 'https://www.facebook.com/april.shop.insta', city: 'Paphos', category: 'Clothes', lat:  34.75685601994596, long: 32.41235882796452, description: '"April" is a boutique clothes shop nestled in the heart of a bustling city, known for its vibrant and seasonal collections that mirror the freshness and renewal of spring. This whimsical store specializes in ethereal fabrics and contemporary designs, offering a range of apparel from breezy sundresses to elegant evening wear. Each piece is carefully selected to embody the joy and optimism of April, with floral patterns and pastel hues dominating the racks. The shop itself, with its soft lighting and rustic décor, invites customers into a world where fashion meets the rejuvenating spirit of spring (photo from Tripadvisor).'),
  Place(name: 'C&S Polyviou Souvenir shop',id: 1126,imagePath: 'paphosShop/cs.png', city: 'Paphos', category: 'Souvenir Shop',url: 'https://www.tripadvisor.com.gr/Attraction_Review-g190384-d26767273-Reviews-C_and_S_Polyviou_souvenir_shop-Paphos_Paphos_District.html', lat: 34.77881490245437, long: 32.41945944264625, description: 'Tucked away in the scenic heart of Paphos, the C&S Polyviou Souvenir Shop offers visitors a delightful array of traditional Cypriot crafts and souvenirs. As you step into the warmly lit interior, you\'re greeted by the rich aroma of local herbs and the inviting smiles of the shop\'s owners, Christos and Sophia Polyviou, whose passion for Cypriot culture is evident in every corner of their carefully curated store.Walls adorned with intricate lacework, handwoven by skilled artisans from the villages, beckon for closer inspection. Shelves brim with colorful pottery, each piece uniquely hand-painted with designs inspired by ancient Cypriot art and the azure hues of the Mediterranean Sea. The air is perfumed with the scent of locally sourced lavender and rosemary, packaged alongside an assortment of traditional Cypriot spices, perfect for adding a dash of Cyprus to your cooking.',),
  Place(name: 'Vivere Boutique',id: 1127, imagePath: 'paphosShop/vivere.png',url: 'https://www.facebook.com/VivereBoutiquePaphos/', category: 'Clothes', city:'Paphos', lat: 34.77946832272615, long: 32.42179944092998, description: 'Vivere Boutique is a fashion destination that transcends simple clothing to offer high aesthetic quality pieces, focusing on feminine expression across all its collections. They provide a range of options for daily needs, luxury/evening wear, and more demanding moments, ensuring a blend of modern and quality clothing items.')
,Place(name: 'Crystal Shop Cyprus',id: 1128, imagePath: 'paphosShop/crystal.png',category: 'Souvenir Shop', city: 'Paphos', lat:34.76648939696741, long: 32.410360589742915 ,url: 'https://www.crystalshopcyprus.com/', description: 'Crystal Shop Cyprus, located in Paphos, offers a wide range of crystals, gemstones, and related products. They provide online shopping with delivery across Cyprus, including major cities like Limassol, Larnaca, Nicosia, and more. The shop caters to various needs with products such as tumblestones, birthstones, incense sticks, and smudge sticks, among others (photo from Tripadvisor).')
];
List<Place> LarnacaShops= [
Place(name: 'I Love Larnaca', url: 'https://www.facebook.com/iLoveLarnca/?locale=el_GR',id: 1129,imagePath: 'larnacaShops/love.png', city: 'Larnaca', category: 'Souvenir Shop',lat: 34.9110744458279, long: 33.637653855133365, description: 'It seems I encountered an issue accessing more information about the "I Love Larnaca" souvenir shop directly. However, based on its name, it\'s likely a shop that specializes in a wide range of souvenirs and gifts that reflect the beauty and culture of Larnaca. These could include locally made crafts, jewelry, traditional Cypriot items, and exclusive designs that celebrate the love for Larnaca. Such shops often provide visitors with memorable keepsakes from their travels, from handcrafted items by local artisans to unique finds that capture the essence of the place. If you\'re in Larnaca, it might be worth a visit to pick up something special that reminds you of your time in this beautiful city.')
,Place(name: 'Sirocco Fashion Center Ltd',imagePath: 'larnacaShops/sirocco.png',id: 1131, url: 'https://sirocco.com.cy/', lat: 34.93212110179539, long: 33.63763249941366, category: 'Clothes', city: 'Larnaca', description: 'SIROCCO Fashion Center LTD is renowned for its extensive collection of women\'s and men\'s clothing, offering a wide range of fashion items and accessories. With a focus on contemporary trends, the shop features an impressive selection of shoes, bags, and leather accessories, catering to diverse styles and preferences. It\'s a go-to destination for those looking to update their wardrobe with quality and stylish pieces (photo from 2BelnStore).')
,Place(name: 'Placci', imagePath: 'larnacaShops/placci.png',id: 1132,url: 'https://www.facebook.com/placcilarnaca/', lat:  34.91515616379129, long: 33.634197253630866, category: 'Clothes', city: 'Larnaca', description: 'Placci in Larnaca is a boutique clothing store specializing in women\'s fashion. It offers a diverse selection of clothing, footwear, and leather goods, catering to a variety of styles and preferences. The store is known for its focus on quality and the latest trends, aiming to provide customers with a unique shopping experience. As part of the retail trade sector, it distinguishes itself through personalized customer service and a curated collection of fashion pieces (photo from 2BelnStore).'),
  Place(name: 'Acappela',imagePath: 'larnacaShops/acappela.png', url: 'https://acappela.com.cy/',id: 1133, lat: 34.91674337513005, long: 33.634639161341845, city: 'Larnaca', category: 'Music Store', description: 'Acappela Music Store is a leading destination for music enthusiasts, offering an extensive selection of DVDs, CDs, video games, electronics, and computers among other related items. Recognized as the No.1 provider in Cyprus, the store caters to a wide range of entertainment needs. Beyond retail, Acappela plays a significant role in the local entertainment scene by facilitating access to tickets for major events on the island, making it a central hub for both acquiring entertainment products and engaging with the island’s cultural events.')
, Place(name: 'Angys Shop',imagePath: 'larnacaShops/angys.png',id: 1134, url: 'https://www.facebook.com/angys.shop.cy/', lat:34.915037038264984, long: 33.636298371772355, category: 'Clothes', city: 'Larnaca', description: 'Angys Shop is a charming boutique nestled in the heart of a bustling city, known for its eclectic mix of unique and handmade items. Specializing in artisanal crafts, vintage finds, and bespoke fashion, the shop offers an array of products designed to appeal to the discerning shopper looking for something truly special. From hand-painted ceramics and locally designed jewelry to custom-tailored garments and one-of-a-kind home décor, Angys Shop provides a treasure trove of items that celebrate craftsmanship and creativity.' )
];
List<Place> getShops (String city) {
  if (city == 'Nicosia') {
    return NicosiaShops;
  }
  else if (city == 'Limassol') {
    return limassolShops;
  } else if (city == 'Famagusta') {
    return famagustaShops;
  } else if (city == 'Paphos') {
    return PaphosShops;
  } else if (city == 'Larnaca') {
    return LarnacaShops;
  }
  else {
    return NicosiaShops;
  }}
}