import 'package:tourismappofficial/Places/place.dart';

class Sights {
  List<Place> famagustaSights = [
    Place(name: 'MUSAN Museum of Underwater Sculpture Ayia Napa',id: 4010,imagePath: 'famagustaSight/musan.jpg',url: 'https://musan.com.cy/', city: 'Ayia Napa, Famagusta', category: 'Museum', lat:34.98520509943173, long: 33.98380366080352, description: 'The MUSAN (Museum of Underwater Sculpture Ayia Napa) is an innovative underwater museum located off the coast of Ayia Napa, Cyprus. Opened in 2021, it features a collection of over 90 sculptures created by British artist Jason deCaires Taylor. These artworks are strategically placed at various depths beneath the sea surface, inviting scuba divers and snorkelers to explore an ethereal, submerged gallery. The sculptures are designed to be eco-friendly, made from materials that encourage marine life to inhabit and interact with them, thus serving dual purposes of art and artificial reef creation. This unique setup not only enhances the marine environment but also aims to alleviate pressure on natural reefs by diverting tourists to the sculptural installations. MUSAN offers a surreal experience, merging art, conservation, and recreation in a captivating underwater setting (photo from Jason deCaires Taylor).' ),
    Place(name: 'Cape Greco National Forest Park',url: 'https://visitfamagusta.com.cy/cape-greko-national-forest-park/', imagePath: 'famagustaSight/capegreco.jpg', lat: 34.97212467458134, long: 34.072034906230805, id: 175, category: 'Park', city: 'Ayia Napa, Famagusta', description: 'Cape Greco National Park, located on the southeastern coast of Cyprus, is a captivating blend of natural beauty and mythology. Established as a National Forest Park in 1993, it covers an area of 385 hectares, showcasing a diverse range of flora and fauna, geological wonders, and mythological significance (photo from Nissi Beach Resort). '),
    Place(name: 'Parko Paliatso Luna Park', imagePath: 'famagustaSight/paliatso.jpg',url:'https://www.parkopaliatsocy.com/', lat:34.98551270481741, long: 33.997701627414216, id: 176, city: 'Ayia Napa, Famagusta', category: 'Luna Park', description: 'Parko Paliatso Luna Park, established in 1999 and located in Ayia Napa, Cyprus, is the largest amusement park in the country, sprawling over an area of 30,000 square meters. The park features more than 25 rides, catering to all ages and preferences. It offers a diverse array of attractions, including extreme rides for thrill-seekers, family rides for all ages, and kiddie rides suitable for younger children (photo from Cyprus Alive).'),
    Place(name: 'Municipal Museum Thalassa', imagePath: 'famagustaSight/museum.jpg', lat: 34.9875230945821,long: 34.00262558037847, id: 177, city: 'Ayia Napa, Famagusta', category: 'Museum', description: 'The Thalassa Museum in Ayia Napa, Cyprus, is an impressive cultural institution dedicated to showcasing the maritime heritage and marine life of the region. Opened in August 2005, the museum is a collaborative effort managed by the Pieride Foundation, in partnership with the Greek Institute of Naval Tradition Protection and the Foundation of Seal Life Tornarite – Pieride.', url: 'https://thalassamuseum.org.cy/'),
    Place(name: 'WaterWorld Themed Waterpark', imagePath: 'famagustaSight/water park.jpg', lat: 34.98509056547136, long: 33.943439912431394, id: 178, category: 'Water Park', city: 'Ayia Napa, Famagusta', description: 'WaterWorld Themed Waterpark in Ayia Napa, Cyprus, is a major attraction known for its Ancient Greek theme. It\'s one of the largest themed water parks in Europe, boasting more than 25 rides and attractions. The park includes a wide selection of rides suitable for all ages, food outlets, and souvenir shops, providing a comprehensive entertainment experience.', url: 'https://waterworldwaterpark.com/')
    ,Place(name: 'Church of Profitis Elias',url: 'https://www.tripadvisor.com/Attraction_Review-g667803-d4358158-Reviews-Church_of_Profitis_Elias-Protaras_Paralimni_Famagusta_District.html', imagePath: 'famagustaSight/profitis elias.jpg', lat:35.018489118730734, long: 34.04119243264172, id: 179, city: 'Protaras, Famagusta', category: 'Church', description: 'The Church of Profitis Ilias, located near Protaras in Cyprus, is an architecturally beautiful and historically significant site. Built in 1984, it replaced an older chapel and is known for its traditional stone construction, which harmonizes seamlessly with the natural surroundings. The church stands on a granite rock and is renowned for its elevated position that offers stunning panoramic views of the Protaras area and the sea. To reach the church, visitors must ascend a steep staircase with 153 steps, but the effort is rewarded with breathtaking vistas (photo from Tripadvisor).'),
    Place(name: 'Agioi Saranta Cave Church',url: 'https://cypruspassion.net/ayioi-saranta-cave-church/', imagePath: 'famagustaSight/church.jpg', lat: 35.00502496965207,long: 34.03630023422185, id:180, city: 'Protaras, Famagusta', category:'Church/Cave',description: 'The Agioi Saranta Cave Church, located near Protaras in the Famagusta district of Cyprus, is a unique and historically significant religious site. Tucked away in a cave, it offers a blend of natural beauty and spiritual significance.' )
  ];

  List<Place> limassolSights = [
    Place(name: 'Molos', imagePath: 'limassolsights/molos.jpg',url: 'https://allaboutlimassol.com/en/limassol-molos', lat: 34.67510152420617, long: 33.048253828095476, id: 181, city: 'Limassol', category: 'Seaside Park', description: 'Molos in Limassol is a multifunctional seaside park that represents one of the most beautiful and largest parks in the Mediterranean region. Extending along the Akti Olympion beach to the old Limassol Port, it covers an area of 65,000 square meters. The park is a significant part of Limassol\'s identity as a seaside town, particularly after the completion of the new projects along Akti Olympion (photo from AboutLimassol).'),
    Place(name: 'Limassol Marina',  imagePath: 'limassolsights/marina.jpg', lat: 34.670146108068145, long: 33.04042881804139, id: 182, city: 'Limassol', category: 'Port', description: 'Limassol Marina, opened in 2014, is a remarkable development in Cyprus that has significantly transformed the image of Limassol. Extending over 40,000 square meters, it stands out as one of the most attractive and outstanding projects in Europe, blending modernity with luxury.', url: 'https://www.limassolmarina.com/'),
    Place(name: 'City Of Dreams Mediterranean',url: 'https://www.cityofdreamsmed.com.cy/en', imagePath: 'limassolsights/casino2.jpg', lat:34.64704784110228,city: 'Limassol',category: 'Casino/Resort', long: 32.99348987699256, id: 10001, description: 'City of Dreams Mediterranean is poised to be Cyprus’s first integrated casino resort, envisioned as a landmark development that blends luxury and entertainment with the cultural charm of the region. Located in Limassol, the resort aims to transform Cyprus into a year-round destination for tourists and gaming enthusiasts alike. The project, spearheaded by Melco Resorts and Entertainment, promises to deliver an unparalleled hospitality experience with its state-of-the-art facilities that include a casino, four luxury hotels, a health and wellness center, an outdoor amphitheater, and extensive retail space.The centerpiece of the resort is the casino, which is designed to cater to a variety of gaming preferences, featuring an extensive selection of slots, gaming tables, and exclusive VIP areas. Complementing the gaming experience, City of Dreams Mediterranean will offer a family-friendly environment with amenities and activities for all ages, including sports facilities, a family adventure park, and lush, landscaped outdoor spaces. The resort is also expected to drive significant economic benefits for Cyprus, including job creation and tourism growth. With its blend of luxury, entertainment, and cultural integration, City of Dreams Mediterranean is set to redefine the leisure and hospitality landscape in Cyprus (photo from Booking).' ),
    Place(name: 'Limassol Castle',url: 'https://www.tripadvisor.com/Attraction_Review-g190382-d527729-Reviews-Limassol_Castle-Limassol_City_Limassol.html', imagePath: 'limassolsights/castle.jpg', lat: 34.67236212571635, long: 33.041546260694005, id: 183, category: 'Castle', city: 'Limassol', description: 'Limassol Castle, nestled in the heart of Limassol\'s historical center near the harbor, is a medieval structure with a rich history that dates back to the Byzantine era. The castle, as it stands today, was mainly rebuilt around 1590 during Ottoman rule, but it rests on foundations that reveal a more complex pas.'),
    Place(name: 'Curium Ancient Theater',url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/rural/sites-monuments/741-theatre-of-kourion', imagePath: 'limassolsights/kourion.jpg', lat: 34.664284667735416, long: 32.887861493726355, id: 184, city: 'Kourion, Limassol', category: 'Ancient Amphitheater', description: 'Curium, an ancient city on the southern coast of Cyprus, is renowned for its magnificent Greco-Roman theater, which dates back to the 2nd century B.C. This theater, carved into the side of a hill, overlooks the Mediterranean Sea, offering a stunning backdrop to the performances that were once held here. It could originally seat around 3,500 spectators, but extensions in the Roman period increased its capacity to about 6,000 (photo from Visit Cyprus).' ),
    Place(name: 'Kolossi Medieval Castle',url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/rural/sites-monuments/2401-kolossi-medieval-castle', imagePath: 'limassolsights/Kolossi_Castle_01.jpg', lat:34.66513798279181, long: 32.934089472915176, id: 185, category: 'Castle', city: 'Kolossi, Limassol', description: 'Kolossi Castle is a fine example of military architecture from the Middle Ages, located near Limassol, Cyprus. Originally built in the 13th century by the Knights of St. John of Jerusalem, the castle has undergone several phases of reconstruction and modification, particularly in the 15th century under the Hospitaller Knights.')
    ,Place(name: 'Troodos Mountains',url: 'https://www.tripadvisor.com/Attraction_Review-g3870266-d10721431-Reviews-Troodos_Mountains-Troodos_Limassol.html', imagePath: 'limassolsights/trppdps.JPG', lat:34.92264932869189, long: 32.8812273928868, id: 186, city: 'Troodos, Limassol', category: 'Mountains', description: 'The Troodos Mountains, located in southern Cyprus, are a significant geographical and cultural landmark of the region. This mountain range, rising to its highest point at Mount Olympus or Khionistra (6,401 feet), is notable for its geological significance and rich biodiversity. The mountains are formed mainly of igneous rock and are characterized by steep valleys covered with diverse vegetation, such as pine, cypress, dwarf oak, and cedar. These natural features are protected as state forests.' ),
     Place(name: 'Fasouri Watermania Water Park', imagePath: 'limassolsights/fasouri.jpg', lat: 34.65201063662752, long: 32.973688059024454, id: 5001, city: 'Fasouri, Limassol', category: 'Water Park', description: 'Fasouri Watermania, located in Fasouri near Limassol, Cyprus, is the largest waterpark on the island. It was established in 1999 and spans over 100,000 square meters. The park features a Polynesian theme, offering a tropical atmosphere. It houses numerous attractions suitable for all ages, including slides like the Free Fall Kamikaze and the Black Hole, a lazy river, and a wave pool. The park also has facilities such as two restaurants, three snack bars, and 2,000 sunbeds. Fasouri Watermania is known for its environmental consciousness and has received several accolades, including Europe\'s Leading Waterpark Attraction at the 2007 World Travel Awards (photo from CyprusForTravellers).', url: 'http://www.fasouri-watermania.com/en/')
    ,Place(name: 'My Mall Limassol', imagePath: 'limassolsights/mymall.jpg', lat: 34.65293085799345, long: 32.99801974568849, id: 5003, category: 'Mall', city: 'Zakaki, Limassol', description: 'MY MALL Limassol, located in the Zakaki suburb of Limassol, Cyprus, is known as the second largest mall in Cyprus. Opened in 2009, it was initially named "Tiffany Mall" but changed its name following trademark issues. The mall boasts over 140 stores and services, spread across a total retail floor area of 48,000 square meters. It offers a diverse range of facilities, including an ice rink, bowling alley, arcade, 6D Cinema, and a play area. A food court is also available, providing various dining options. MY MALL Limassol is accessible by public transit, with a shuttle bus service running between the mall and major hotels in Limassol, and dedicated bus routes by EMEL connecting it to the city (photo from Kathimerini).', url: 'https://www.mymall.com.cy/')
     ,Place(name: 'Limassol Zoo', imagePath: 'limassolsights/zoo.jpg', lat: 34.683554431470604, long: 33.05586438433135, id: 191, city: 'Limassol', category: 'Zoo', description: 'The Limassol Zoo, located in Limassol, Cyprus, is one of the largest zoos in Europe. It was extensively renovated and reopened in 2012. The zoo is home to a diverse range of beautiful and interesting animals, birds, and reptiles from all continents. It provides visitors with an educational experience through organized lectures, guided tours, and updates about wildlife and fauna. The zoo also plays a crucial role in research, protection, reproduction, and release of endangered species. Additionally, the zoo includes a cafeteria named “Flamingo” and a modern playground, enhancing the visitor experience. It\'s open throughout the year with varying visiting hours according to the season.', url: 'https://limassolzoo.com/')
     , Place(name: 'Alphamega Stadium', imagePath: 'limassolsights/alphamega-stadium.jpg', lat:34.69346163390836, long: 32.93919056237097, id: 207, category: 'Football Stadium', city: 'Kolossi, Limassol', description: 'The Alphamega Stadium, also known as Limassol Stadium for UEFA competitions, is a significant football stadium in Kolossi, Limassol District, Cyprus. It\'s notable for being the home ground of three of Limassol\'s largest football clubs: Apollon, AEL, and Aris. The stadium\'s construction began on January 28, 2019, following the signing of construction contracts with the Cyfield – Neophytou J.V. joint venture. The official inauguration of the Alphamega Stadium occurred on November 25, 2022.' ,url: 'https://www.facebook.com/AlphamegaStadium/')
    ,Place(name: 'Kykkos Monastery',id: 8000,url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites-monuments/263-kykkos-monastery', imagePath: 'nicosiasights/kykkos.jpg', lat: 34.98459283765119, long:32.74267576569819, category: 'Church', city: 'Troodos Mountains', description: 'The Kykkos Monastery, located in the Troodos Mountains of Cyprus, is one of the island\'s most famous and richly adorned monasteries. Founded in the 11th century by Byzantine Emperor Alexios I Komnenos, the monastery is dedicated to the Virgin Mary. Its most prized possession is an icon of the Virgin Mary, reputedly painted by Saint Luke, which is covered in silver gilt and held in high reverence. The monastery’s architecture is a stunning display of ornate frescoes, golden icons, and intricate mosaics, which make it a major pilgrimage site and a beacon of Orthodox Christian faith. Additionally, Kykkos Monastery is surrounded by a lush forest, adding a serene natural beauty to its spiritual ambiance. The monastery also houses a museum that exhibits religious relics, icons, and other artifacts, further enriching the cultural and religious experience for visitors (photo from Cyprus Alive).')
  ];

  List<Place> nicosiaSights = [
    Place(name: 'Church of Agios Kyprianos', url: 'https://www.menico.org/en/what-to-know-ten/religious-life-ten/agioukyprianou-ten.html', imagePath: 'nicosiasights/meniko.jpg', lat: 35.109330533272896, long: 33.14398069343252, id: 8020, category: 'Church', city: 'Menico, Nicosia', description: 'The Church of Agios Kyprianos in Menico, Cyprus, is a notable religious site with a rich historical background. This church, also dedicated to Agia Ioustini, is one of the few Orthodox churches honoring these saints. Constructed during the 16th century by the Franks, it is linked to a legend of a Frankish king cured of fevers after worshiping the Holy Heads and drinking holy water. The church has undergone various reconstructions and renovations, notably starting in 2008, which have slightly altered its original form.The architecture of the church includes features from different eras, including a basilica with ogive arches and staurolites, a striking bell tower, and parts of the building dating back to the 14th century. Inside, the church houses a wooden iconostasis from 1818, embellished with depictions of birds, animals, and plants, focusing on pergolas and grapes, which adds a unique artistic element to the sacred space.')
    ,Place(name: 'Cyprus Museum',url: 'https://www.nicosia.org.cy/en-GB/discover/museums/cyprus-museum/', imagePath: 'nicosiasights/museumc.jpg', lat: 35.1717237619523, long: 33.35571570033155, id: 187, category: 'Museum', city: 'Nicosia', description: 'The Cyprus Museum, also known as the Cyprus Archaeological Museum, is a significant cultural institution in Nicosia, Cyprus. It holds the distinction of being the oldest and largest archaeological museum on the island. The museum\'s foundation dates back to 1882, during the British occupation of Cyprus, in response to a petition by the Cypriot people. This action was largely motivated by concerns over illicit excavations and the smuggling of antiquities off the island.'),
    Place(name: 'Ledra Street', imagePath: 'images/City0.jpg',url: null, lat: 35.173890780640676, long: 33.36168301745709, id: 188, city: 'Nicosia', category: 'Street', description: 'Ledra Street, situated in the southern part of Nicosia, Cyprus, is a bustling commercial and cultural hub known for its vibrant atmosphere and historical significance. This pedestrian-only street has been a key location in the city since its pedestrianization in 1998, creating a pleasant environment for shopping and leisure.'),
   Place(name: 'Church of God',imagePath: 'nicosiasights/godchurch.jpg',lat:35.161421034289255, long:33.34927678697038 ,url: 'https://www.peneek.com/nicosia', id:4014,category: 'Church',city: 'Nicosia', description: 'The Church of God of Prophecy, located at 3 Olympiados Street, CY-2063 Strovolos, Cyprus, offers its services in the Greek language. The church is part of a wider network that emphasizes prophecy, worship, and the teachings of the Gospel, catering to the spiritual needs of its community.')
   ,Place(name: 'Kykkos Monastery',id: 8000,url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites-monuments/263-kykkos-monastery', imagePath: 'nicosiasights/kykkos.jpg', lat: 34.98459283765119, long:32.74267576569819, category: 'Church', city: 'Troodos Mountains', description: 'The Kykkos Monastery, located in the Troodos Mountains of Cyprus, is one of the island\'s most famous and richly adorned monasteries. Founded in the 11th century by Byzantine Emperor Alexios I Komnenos, the monastery is dedicated to the Virgin Mary. Its most prized possession is an icon of the Virgin Mary, reputedly painted by Saint Luke, which is covered in silver gilt and held in high reverence. The monastery’s architecture is a stunning display of ornate frescoes, golden icons, and intricate mosaics, which make it a major pilgrimage site and a beacon of Orthodox Christian faith. Additionally, Kykkos Monastery is surrounded by a lush forest, adding a serene natural beauty to its spiritual ambiance. The monastery also houses a museum that exhibits religious relics, icons, and other artifacts, further enriching the cultural and religious experience for visitors (photo from Cyprus Alive).')
    ,Place(name: 'Machairas Monastery',url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/rural/sites-monuments/720-machairas-monastery', imagePath: 'nicosiasights/machairas.jpg', lat: 34.940629391677504, long: 33.191176426670296, id: 189, category: 'Monastery', city: 'Machairas, Nicosia', description: 'Machairas Monastery, dedicated to the Virgin Mary, is a significant historical and religious site in Cyprus. Located approximately 40 km from Nicosia, the capital of Cyprus, it stands at an altitude of around 900 meters near the village of Lazanias.The monastery\'s origins are steeped in legend, which tells of two hermits from Palestine, Neophytos and Ignatius, who discovered a hidden icon of the Virgin Mary in a cave around 1145. This icon, believed to be one of the seventy painted by the Apostle Luke, was accessed by cutting through thick plant growth with a knife, hence the name Machairotissa (photo from Cyprus Alive).'),
  Place(name: 'Troodos Mountains',url: 'https://www.tripadvisor.com/Attraction_Review-g3870266-d10721431-Reviews-Troodos_Mountains-Troodos_Limassol.html', imagePath: 'limassolsights/trppdps.JPG', lat:34.92264932869189, long: 32.8812273928868, id: 186, city: 'Troodos, Limassol', category: 'Mountains', description: 'The Troodos Mountains, located in southern Cyprus, are a significant geographical and cultural landmark of the region. This mountain range, rising to its highest point at Mount Olympus or Khionistra (6,401 feet), is notable for its geological significance and rich biodiversity. The mountains are formed mainly of igneous rock and are characterized by steep valleys covered with diverse vegetation, such as pine, cypress, dwarf oak, and cedar. These natural features are protected as state forests.' ),
    Place(name: 'Nicosia Mall', imagePath: 'nicosiasights/nicosia-mall.jpg', lat:35.13464192135805, long: 33.27917091752734, id: 5005, city: 'Nicosia', category: 'Mall', description: 'Nicosia Mall, located in the Lakatamia-Anthoupolis area in the southwest of Nicosia, Cyprus, opened its doors in November 2018. It is the largest mall in Cyprus, boasting over 140 stores and services spread across a retail floor area of 82,000 square meters. The mall provides a diverse shopping experience with a wide range of outlets on three floor levels, complemented by ample parking for 1,700 vehicles. Additionally, Nicosia Mall includes a food market and a six-screen Rio Premier cinema, enhancing its appeal as a shopping and leisure destination (photo from Scala).', url: 'https://www.nicosiamall.com/' )
    ,Place(name: 'The Mall of Cyprus', imagePath: 'nicosiasights/1the_mall_of_cyprus_1.jpg', lat:35.130267390900414, long: 33.37091145354887, id: 190, city: 'Nicosia', category: 'Mall', description: 'The Mall of Cyprus, opened in September 2007, is the first shopping mall of its kind in Cyprus. Located at the entrance of Nicosia, it\'s conveniently accessible from the Nicosia-Limassol/Larnaca highway. The mall covers an area of 27,000 square meters and features a variety of retail stores including international brands . It also hosts a range of restaurants, cafeterias, and entertainment options such as a cinema. The Mall of Cyprus is a part of the Shacolas Emporium Park, a modern shopping complex, and is a popular destination for retail and entertainment, attracting over 5.5 million visitors annually (photo from AlphaNews).', url: 'https://mallofcyprus.com/')
    ,Place(name: 'GSP Stadium', imagePath: 'nicosiasights/gsp_top.jpg', lat: 35.11452063559227, long: 33.36287909044829, city: 'Nicosia', category: 'Football Stadium', id:206, description: 'The GSP Stadium, located in Strovolos, Nicosia District, Cyprus, is the largest stadium in the country with a capacity of 22,859. It opened in 1999 and is the home stadium for three of Nicosia\'s biggest football clubs: APOEL, Olympiakos, and Omonia. Additionally, it has been used by the Cyprus national football team. The stadium is unique in Cyprus as it fully complies with UEFA requirements and is often used for European matches by Cypriot teams. The design includes a football stadium, an athletics stadium, and an auxiliary football pitch for training, making it a versatile sports venue.', url: 'https://www.gsp.org.cy/')
  ,Place(name: 'C2 Nicosia - Cyprus Casinos', imagePath:'nicosiasights/c2.jpg', lat: 35.16461840720185, long: 33.32452678263749, category: 'Casino', city: 'Nicosia', id: 10000,url:'https://www.cypruscasinos.com/en' , description: 'C2 Casino in Nicosia, Cyprus, offers an exciting and upscale gaming experience that attracts both locals and tourists. Situated in the heart of the city, the casino is part of the larger City of Dreams Mediterranean resort, which is renowned for its luxurious amenities and vibrant atmosphere. The casino features a wide array of gaming options, including numerous slot machines, classic table games like blackjack, roulette, and poker, and often hosts live entertainment events. The sophisticated interior design combines contemporary elegance with touches of local culture, creating a welcoming yet thrilling ambiance.Beyond gaming, C2 Casino provides a comprehensive leisure experience. The venue includes a variety of dining options, from casual snacks to fine dining restaurants, catering to all tastes and occasions. Additionally, guests can enjoy a cocktail at one of the stylish bars or relax in the exclusive VIP gaming areas, which offer a more private atmosphere. The casino prides itself on high standards of service and security, ensuring a safe and enjoyable environment for all its patrons. With its combination of luxury, excitement, and exceptional customer service, C2 Casino stands out as a premier destination for entertainment in Nicosia.' )
  ];

  List<Place> paphosSights = [
    Place(name: 'Petra Tou Romiou ',url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/rural/sites-monuments/732-birthplace-of-aphrodite-petra-tou-romiou', imagePath: 'paphosSight/petratouromiou.jpg', lat: 34.66366112076574, long: 32.62717222471947 , id:32, category:'Sight',city:'Paphos',description: 'Petra tou Romiou, also known as Aphrodite\'s Rock, is a fascinating and mythologically rich beach located in the Paphos district of Cyprus, easily visible along the coastal road between Paphos and Limassol. This famous site draws thousands of visitors each year, enchanted both by its natural beauty and the legends that surround it.The area is steeped in mythology, primarily associated with the birth of Aphrodite, the Greek goddess of love and beauty. One of the most captivating legends suggests that Aphrodite emerged from the sea at this specific bay. According to myth, she first traveled to the island of Kythera but eventually reached Cyprus, choosing Paphos as her point of emergence. It\'s believed that Aphrodite’s Rock and the surrounding rocks were part of a great shell that carried the goddess to the shores of Cyprus. This myth has led to the belief that swimming around Aphrodite’s Rock three times will bless one with eternal youth, beauty, and good fortune.')
   , Place(name: 'Kato Paphos Archaeological Park', imagePath: 'paphosSight/paphoskato.jpg',url: 'https://www.tripadvisor.com/Attraction_Review-g190384-d527731-Reviews-Kato_Paphos_Archaeological_Park-Paphos_Paphos_District.html', lat: 34.756051820089596, long: 32.408464203802765, id: 192, category: 'Archaeological Park', city: 'Paphos', description: 'The Archaeological Park of Kato Pafos in Cyprus, a UNESCO World Heritage Site since 1980, is one of the island\'s most important archaeological locations. It encompasses a vast area that includes a range of historical periods, with most remnants dating back to the Roman era. Highlights of the park include the intricate mosaic floors of four Roman villas - the Houses of Dionysos, Theseus, Aion, and Orpheus, which are adorned with scenes from Greek Mythology. Other significant structures in the park include the Asklepieion, the Odeon, the Agora, and the Saranta Kolones Castle. The park is a key destination for those interested in ancient history and archaeology (photo from Tripadvisor).'),
    Place(name: 'Church of Agia Kyriaki and post St. Paul',url: 'https://www.tripadvisor.com/Attraction_Review-g190384-d6503324-Reviews-Church_of_Agia_Kyriaki_and_post_St_Paul-Paphos_Paphos_District.html', imagePath: 'paphosSight/churchofayia.jpg', lat: 34.75785760248215,long: 32.41419483023269, id: 193, city: 'Paphos', category: 'Church', description: 'The Church of Agia Kyriaki, also known as The Church at St. Paul’s Pillar, holds significant historical and religious importance. It is located in Kato Pafos (Paphos), Cyprus. This site is renowned for its connection to the apostles Paul and Barnabas, who visited Cyprus around 45 AD. Tradition holds that St. Paul was flogged near this church, leading to its association with St. Paul\'s Pillar (photo from Tripadvisor).')
    ,Place(name: 'Kelefos Bridge', imagePath: 'paphosSight/kelefos-bridge.jpg', lat:34.88946838890026,long: 32.74745457429207,url: 'https://www.tripadvisor.com.gr/Attraction_Review-g8550766-d8540152-Reviews-Kefalos_Bridge-Agios_Nikolaos_Paphos_District.html', category: 'Bridge', city: 'Agios Nikolaos, Paphos', id: 194, description: 'The Kelefos Bridge, situated in the Paphos region of Cyprus, is a well-known Venetian bridge, admired for its historical significance and picturesque setting. This medieval structure spans the Diarizos River and is located near the village of Agios Nikolaos, nestled in the southwestern corner of the Paphos Forest. The bridge was constructed between 1489 and 1571, a period when Cyprus was engaged in the copper trade with Egypt, exchanging it for silk and gold.' )
    ,Place(name: 'Paphos Aphrodite Waterpark', imagePath: 'paphosSight/parkwaterpaphos.jpg', category: 'Water Park', city:'Geroskipou, Paphos',lat:34.74174168881717, long: 32.44085957120281, id: 195, description: 'The Paphos Aphrodite Waterpark, known as the largest waterpark in the Paphos region, offers a unique and exciting aqua adventure. Located in Kato Paphos along the coastal road, it\'s easily accessible by both car and local bus services.The waterpark is packed with a variety of attractions to cater to all ages and preferences. Thrill-seekers can enjoy high-speed water slides, including the standout Kamikaze slides, while those looking for relaxation can drift along the extensive lazy river or lounge on one of the 1000 sunbeds available at no extra charge. For families, there\'s a dedicated kids’ water-play area, ensuring fun for the younger visitors as well (photo from Tripadvisor).', url: 'https://aphroditewaterpark.com/'),
    Place(name: 'Tombs of the Kings', imagePath: 'paphosSight/tomps.jpg',url: 'https://www.tripadvisor.com/Attraction_Review-g190384-d313655-Reviews-Tombs_of_the_Kings-Paphos_Paphos_District.html', city: 'Chlorakas, Paphos', category: 'Ancient Ruins', lat: 34.77495215537632, long: 32.4072265049152, id: 196, description: 'The Tombs of the Kings in Paphos, Cyprus, is a significant ancient necropolis located about two kilometers north of the Paphos harbor. Despite its name, the site is not the burial place of actual kings, but rather of Paphitic aristocrats and high officials. This historical site dates back to the 4th century BC and was designated as a UNESCO World Heritage Site in 1980, highlighting its cultural and historical importance (photo from Tripadvisor).')
   , Place(name: 'Pafos Zoo', imagePath: 'paphosSight/pafoszoo.jpg', lat: 34.89382067982927,long: 32.3424900633164, id: 197, category: 'Zoo', city: 'Pegeia, Paphos', description: 'Paphos Zoo in Cyprus offers an enriching wildlife experience, showcasing a diverse range of animals and birds from around the globe. Established by Mr. Christos Christoforou, it was initially intended to house his extensive collection of birds but was later opened to the public in September 2003. Covering over 100,000 square meters of natural environment, Paphos Zoo is the first and largest licensed zoo in Cyprus. It has become one of the island\'s premier tourist attractions, notable for its large collection of parrots and venomous snakes, one of the largest in Europe.', url: 'https://www.pafoszoo.com/'),
  Place(name: 'Kings Avenue Mall', imagePath: 'paphosSight/kings-avenue-mall.jpg', lat:34.7655709698905, long: 32.41371416457734, id: 198, city: 'Paphos', category: 'Mall', description: 'Kings Avenue Mall in Paphos is a popular shopping destination, boasting over 120 stores that range from high-street to designer brands. It\'s not only a shopping hub but also offers a variety of dining options with a global choice of cuisine. Besides shopping and dining, the mall features entertainment facilities like a multiplex cinema with six screens and an arcade. Architecturally, the mall stands out with its exquisite design, making it a modern and inviting space for both local residents and tourists (photo from Tripadvisor).', url: 'https://kingsavenuemall.com/' ),
    Place(name: 'Lara Bay Turtle Conservation Station',url:'https://www.tripadvisor.com/Attraction_Review-g190384-d3398669-Reviews-Lara_Bay_Turtle_Conservation_Station-Paphos_Paphos_District.html' , imagePath: 'paphosSight/turtles.jpg', lat: 34.90912216935836, long: 32.32459456448935, id:199, category: 'Beach', city: 'Akamas, Paphos', description: 'The Lara Bay Turtle Conservation Station in Paphos, Cyprus, is dedicated to protecting and conserving sea turtles. This facility focuses on helping baby turtles safely hatch and make their way to the sea. It is managed by the state\'s department of Forests and Fishery. During the turtle hatching season, visitors may see water tanks containing newly hatched turtles at the station. The conservation efforts here are particularly important as the turtles belong to endangered species, and the station plays a crucial role in protecting the turtles\' eggs from natural predators and human disturbances (photo from AllPlacesToVisit.com).')
   ,Place(name: 'Adonis Baths Waterfalls', imagePath: 'paphosSight/adonis.jpg', lat:34.871318405809454,long: 32.43573429841918, id: 5008, city: 'Koili, Paphos', category: 'Waterfalls', description: 'Adonis Baths Waterfalls is a captivating natural attraction situated in Cyprus. Nestled amidst lush greenery and imposing cliffs, this waterfall offers a visually stunning experience. It cascades down, creating a mesmerizing spectacle enhanced by the sound of water and the earthy scent of wet rocks. The sunlight reflecting off the water\'s surface adds to the enchanting atmosphere.',url: 'https://adonisbathswaterfalls.com/'),


  ];

  List<Place> larnacaSights = [
    Place(name: 'Metropolis Mall', imagePath: 'larnacaSight/metropolis.jpg', lat: 34.924552642676616, long: 33.60539781041449, id: 200, city: 'Larnaca', category:'Mall', description: 'Metropolis Mall in Larnaca, Cyprus, which opened in September 2021, has quickly established itself as a major shopping and entertainment hub. This expansive, single-level mall, built at a cost exceeding 80 million euros, features over 100 shops, including well-known fashion retailers, branded and independent stores. Additionally, it houses a supermarket, a food court with a variety of modern restaurants and cafes, and a diverse range of entertainment options (photo from Kathimerini).',url: 'https://metropolismall.com.cy/'),
    Place(name: 'Agios Lazaros',url: 'https://www.agioslazaros.org/', imagePath: 'larnacaSight/agios lazaros.jpg', lat: 34.91158680974574, long: 33.6348013605627, id: 201, city: 'Larnaca', category: 'Church', description: 'The Church of Saint Lazarus, also known as Agios Lazaros, in Larnaca, Cyprus, is an architectural and historical treasure dating back to the late 9th century. This Byzantine church was built over what is believed to be the tomb of Saint Lazarus, a New Testament figure said to have been resurrected by Jesus. Lazarus, after his resurrection, is believed to have fled to Cyprus, where he was ordained as the first Bishop of Kition (now Larnaca) and lived for an additional 30 years before his second burial in the same location.')
     ,Place(name: 'AEK Arena', imagePath: 'larnacaSight/arena.jpg', lat: 34.9263583055657, long: 33.59802536201406, id: 5009, city: 'Larnaca', category: 'Football Stadium', description: 'The AEK Arena – Georgios Karapatakis is a football stadium in Larnaca, Cyprus. Completed in 2016, it serves as the home ground for AEK Larnaca FC and since 2021, also hosts the home games of the Cyprus national football team. The stadium has a seating capacity of 8,058. Named in honor of Georgios Karapatakis, the father of the President of AEK, Andros Karapatakis, it symbolizes the club\'s respect and tribute. The stadium is noted for its modern design and facilities, making it a significant venue in Cyprus sports landscape (photo from AEK).', url: 'https://aekarena.com.cy/')
    ,Place(name: 'Larnaca Salt Lake',url: 'https://www.tripadvisor.com/Attraction_Review-g190379-d3601049-Reviews-Larnaka_Salt_Lake-Larnaca_Larnaka_District.html', imagePath: 'larnacaSight/aliki.jpg', lat: 34.88591358230172,long: 33.61484596577482, id: 202, city: 'Larnaca', category: 'Lake', description: 'Larnaka Salt Lake, situated to the west of the city of Larnaca, Cyprus, is a unique and fascinating natural attraction. This complex network comprises four salt lakes, namely Aliki, Orphani, Soros, and Spiro, with Aliki being the largest. These lakes collectively form the second-largest salt lake in Cyprus, covering a total surface area of about 2.2 square kilometers. The lake is particularly notable for being a key site for migratory bird watching, including the presence of thousands of flamingos during the winter months, adding a striking pink hue to the landscape (photo from EdelWeiss).', ),
       Place(name: 'Larnaca Marina' ,imagePath: 'larnacaSight/larnmarina.jpg', lat: 34.91735637801528, long: 33.63946829197454, id: 5010, city: 'Larnaca', category: 'Marina', description: 'Larnaca Marina, located in the heart of Larnaca city, is the first marina created in Cyprus and has a long-standing history. It started as a fishing industry and has evolved into a modern facility that can accommodate up to 450 yachts, including yachts over 50 meters in length. The marina is equipped with various amenities including access to water and electricity at each berth, telephone, fax, Wi-Fi (near the office), petrol, and several independent companies providing vessel repair services (photo from Tripadvisor).', url: 'https://larnaca-marina.com.cy')
    ,Place(name: 'The House of Platini', imagePath: 'larnacaSight/platini.jpg', lat: 34.95160394080901, long: 33.427489574240944, id: 203, category: 'Museum',url: 'https://www.tripadvisor.com/Attraction_Review-g190379-d15006029-Reviews-The_House_of_Platini-Larnaca_Larnaka_District.html', city: 'Mosfiloti, Larnaca', description: 'The House of Platini in Larnaca is a specialty museum dedicated to the French former soccer great and former UEFA president Michel Platini. It boasts a vast collection of over 40,000 sporting exhibits, making it a treasure trove for football enthusiasts. Notably, the museum holds two entries in the Guinness World Records. The collection includes a wide range of memorabilia, such as photos, magazines, footballs, t-shirts, and cups. A highlight is the official UEFA suit worn by Platini during his presidency. The museum is unique as it also operates as a kebab tavern in the evening, providing a blend of cultural and culinary experiences (photo from in-Cyprus). '),
     Place(name: 'Hala Sultan Tekke',url: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites-monuments/175-hala-sultan-tekke', imagePath: 'larnacaSight/housan.jpg', lat:34.88553451464119, long: 33.610041481461984, id: 204, category: 'Religious Site', city: 'Dromolaxia, Larnaca', description: 'Hala Sultan Tekke, located on the west bank of Larnaca Salt Lake in Cyprus, is a significant Islamic monument with a rich history. It is revered as one of the most important Islamic sites in the world. The mosque was built over the grave of Umm Haram, believed to be a close relative of the Prophet Mohammed. Umm Haram\'s death, according to tradition, occurred after she fell from a mule during the Arab raids led by the Arab Governor of Syria, Moawiya, around 647 or 649 (photo from flickr).' )
 , Place(name: 'Antonis Papadopoulos Stadium', imagePath: 'larnacaSight/antonis.jpg', lat:34.93739714918563, long: 33.62150247128692 , id: 205, category: 'Football Stadium', city: 'Larnaca', description: 'The Antonis Papadopoulos Stadium is a football stadium located in Larnaca, Cyprus. It was completed in 1986 and serves as the home stadium for Anorthosis Famagusta FC. The stadium has undergone several renovations and expansions since its opening, with the most recent updates in 2008. It currently has a seating capacity of 9,230. Notably, the stadium is equipped with a natural grass playing surface and includes VIP boxes, a press room, dressing rooms, and other modern facilities. It\'s approved by UEFA for European games and has hosted matches of the Cyprus national football team, including notable victories (photo from Football Tripper).', url: 'https://anorthosisfc.com.cy/anorthosis/egkatastasis/stadio-antonis-papadopoulos/')
  ];


//207

  List<Place> getSight(String city) {
    if (city == 'Nicosia') {
      return nicosiaSights;
    } else if (city == 'Limassol') {
      return limassolSights;
    } else if (city == 'Famagusta') {
      return famagustaSights;
    } else if (city == 'Paphos') {
      return paphosSights;
    } else if (city == 'Larnaca') {
      return larnacaSights;
    } else {
      return nicosiaSights;
    }
  }


}

